import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import sharp from 'sharp';

test('album textures and rounded masks share preview/export, preserve photos and transparency, and mount rotated pieces',async({page})=>{
 await fs.mkdir('artifacts/albums',{recursive:true});await page.goto('/');await expect(page.locator('.status-main')).toContainText('Refined preview');
 const sample=await fs.access('Sample/dying-sun.jpg').then(()=>'/Sample/dying-sun.jpg',()=>'/samples/mountain-lake.jpg');
 const thirdSample=await fs.access('Sample/fire-night.jpg').then(()=>'/Sample/fire-night.jpg',()=>'/tests/fixtures/night.png');
 const result=await page.evaluate(async({sample,thirdSample})=>{
  const root='/src/',harnessURL='/tests/browser/harness.ts',hm=await import(harnessURL),h=new hm.Harness(),m=await import(root+'model/project.ts'),edges=await import(root+'model/edge-styles.ts'),albums=await import(root+'model/backgrounds.ts'),geometry=await import(root+'layout/geometry.ts'),adapter=await import(root+'render/adapter.ts');
  await h.source('/tests/fixtures/colour-chart.png');let p=edges.applyEdgeStyle(m.neutral(),'rounded');p=albums.applyBackground(p,'antique');p.composition.fit='cover';p.stage.mounts='black';p.stage.paddingPct=18;
  const a=h.render(p,900,700,'object',false),b=h.render(p,900,700,'object',false),diff=hm.difference;
  const noBackground=m.clone(p);noBackground.stage.material='plain';noBackground.stage.mounts='none';const plain=h.render(noBackground,900,700,'object',false);
  const patch=(x:number,y:number,w:number,hp:number,one:Uint8ClampedArray,two:Uint8ClampedArray)=>{let max=0,sum=0,n=0;for(let yy=y;yy<y+hp;yy++)for(let xx=x;xx<x+w;xx++)for(let k=0;k<4;k++){const d=Math.abs(one[(yy*900+xx)*4+k]-two[(yy*900+xx)*4+k]);max=Math.max(max,d);sum+=d;n++;}return {max,mean:sum/n};};
  const interior=patch(350,250,200,200,a.pixels,plain.pixels),background=patch(15,15,85,650,a.pixels,plain.pixels);
  const transparent=diff(h.render(p,900,700,'object',true).pixels,h.render(noBackground,900,700,'object',true).pixels,true);
  const imageOnly=diff(h.render(p).pixels,h.render(noBackground).pixels,true);
  const changed=m.clone(p);changed.stage.seed+=437;const seeded=patch(15,15,85,650,a.pixels,h.render(changed,900,700,'object',false).pixels);
  const styles:any[]=[];for(const style of albums.backgroundStyles){const q=albums.applyBackground(p,style.id),v=h.render(q,900,700,'flat',false);styles.push({id:style.id,corner:Array.from(v.pixels.slice((25*900+25)*4,(25*900+25)*4+4))});}
  const controls:any={};for(const key of ['texture','aging','stains','edgeShade','binding','textureScale']){const q=m.clone(p);q.stage[key]=key==='textureScale'?2.5:0;controls[key]=patch(15,15,85,650,a.pixels,h.render(q,900,700,'object',false).pixels).mean;}
  const zero=m.clone(p);zero.finishStrength=0;const blank=m.clone(zero);blank.stage.material='plain';blank.stage.mounts='none';const finishZeroBackground=patch(15,15,85,650,h.render(zero,900,700,'flat',false).pixels,h.render(blank,900,700,'flat',false).pixels).mean;
  const clean=m.neutral();clean.edges.enabled=true;clean.edges.strength=100;clean.edges.profile='clean';clean.edges.cornerRadius=9;clean.edges.cornerVariation=0;clean.stage.paddingPct=0;const g=geometry.buildGeometry(clean,600,400),w=Math.round(g.stageWidth),hh=Math.round(g.stageHeight),mask=h.render(clean,w,hh,'flat',true).pixels,alpha=(x:number,y:number)=>mask[(Math.round(y)*w+Math.round(x))*4+3];
  const corner={cut:alpha(g.originX+4,g.originY+4),inside:alpha(g.originX+65,g.originY+65),body:alpha(g.originX+200,g.originY+150)};
  const lo=h.render(p,600,450,'flat',false),hi=h.render(p,1800,1350,'flat',false),down=new OffscreenCanvas(600,450);const dc=down.getContext('2d')!;dc.imageSmoothingQuality='high';dc.drawImage(hi.canvas,0,0,600,450);const previewParity=diff(lo.pixels,dc.getImageData(0,0,600,450).data,true);
  const wa=new adapter.RenderAdapter();await wa.init();const bitmap=await createImageBitmap(await(await fetch('/tests/fixtures/colour-chart.png')).blob());await wa.setSource(bitmap);bitmap.close();const wr=await wa.render(p,{width:900,height:700,view:'object',quality:'export',includeBackground:true,includeShadow:true});const wc=new OffscreenCanvas(900,700);wc.getContext('2d')!.drawImage(wr.bitmap,0,0);wr.bitmap.close();const workerParity=diff(a.pixels,wc.getContext('2d')!.getImageData(0,0,900,700).data,true);wa.dispose();
  await h.source(sample);const outputs:any[]=[];let photo=edges.applyEdgeStyle(m.loadMaterial(m.neutral(),'soft-kozo'),'rounded');photo.composition.aspect='2:3';photo.composition.fit='cover';photo.bw.strength=100;photo.tone.contrast=12;photo.paper.strength=40;photo.ink.spread=0;photo.lighting.strength=70;photo.lighting.relief=50;photo.lighting.shadowOpacity=28;photo.lighting.altitudeDeg=35;photo.stage.paddingPct=3;photo.stage.colour='#E8E8E2';outputs.push({id:'rounded-washi',recipe:photo,...await h.output(photo,2200,'object')});
  for(const style of albums.backgroundStyles.filter((s:{id:string})=>s.id!=='plain')){const q=albums.applyBackground(photo,style.id);q.stage.paddingPct=20;q.stage.mounts=style.id==='charcoal'?'ivory':'black';q.stage.mountSize=7;q.composition.borderPct=3;outputs.push({id:style.id,recipe:q,...await h.output(q,2000,'object')});}
  const pieces=await import(root+'model/pieces.ts'),input=await import(root+'imaging/input.ts');let triptych=albums.applyBackground(photo,'antique');triptych.layout.mode='strips';triptych.layout.photoMode='individual';triptych.layout.gapPct=5;triptych.layout.tearAmount=50;triptych.edges.cornerScope='pieces';triptych.edges.cornerRadius=2.5;triptych.stage.mounts='black';triptych.stage.mountSize=9;triptych.stage.paddingPct=17;triptych.composition.borderPct=1.6;
  const sources:any[]=[];for(const [i,url] of [sample,'/samples/mountain-lake.jpg',thirdSample].entries()){const d=await input.decodeSource(await(await fetch(url)).blob(),url.split('/').at(-1));sources.push(d);const {id,name,width,height,fingerprint}=d.info;triptych=pieces.updatePiece(triptych,pieces.pieceSlots(triptych)[i].key,{source:{id,name,width,height,fingerprint},rotationDeg:i===1?3:-2});}h.renderer.setPieceSources(sources.map(d=>({id:d.info.id,bitmap:d.bitmap})));outputs.push({id:'mounted-sequence',recipe:triptych,...await h.output(triptych,2400,'object')});sources.forEach(d=>d.bitmap.close());h.renderer.setPieceSources([]);
  const trans=await h.output(photo,1800,'object',true);h.renderer.dispose();return {determinism:diff(a.pixels,b.pixels,true),interior,background,transparent,imageOnly,seeded,styles,controls,finishZeroBackground,corner,previewParity,workerParity,outputs,trans};
 },{sample,thirdSample});
 for(const o of result.outputs){await fs.writeFile('artifacts/albums/'+o.id+'.png',Buffer.from(o.base64,'base64'));await fs.writeFile('artifacts/albums/'+o.id+'-settings.json',JSON.stringify(o.recipe,null,2));}
 await fs.writeFile('artifacts/albums/rounded-transparent.png',Buffer.from(result.trans.base64,'base64'));for(const colour of ['#000000','#ffffff','#923ca8'])await sharp('artifacts/albums/rounded-transparent.png').flatten({background:colour}).png().toFile('artifacts/albums/rounded-over-'+colour.slice(1)+'.png');
 const {outputs,trans,...report}=result;await fs.writeFile('artifacts/albums/checks.json',JSON.stringify(report,null,2));
 expect(result.determinism.max).toBe(0);expect(result.interior.max).toBe(0);expect(result.background.mean).toBeGreaterThan(3);expect(result.transparent.max).toBe(0);expect(result.imageOnly.max).toBe(0);expect(result.seeded.mean).toBeGreaterThan(.1);expect(new Set(result.styles.map(s=>s.corner.join(','))).size).toBe(6);Object.values(result.controls).forEach(v=>expect(v).toBeGreaterThan(.01));expect(result.finishZeroBackground).toBeGreaterThan(3);expect(result.corner).toEqual({cut:0,inside:255,body:255});expect(result.previewParity.mean).toBeLessThan(3);expect(result.workerParity.max).toBeLessThanOrEqual(1);
});

test('album and rounded-corner UI: live feedback, undo, saved restoration, real PNG and JPEG exports',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('.status-main')).toContainText('Refined preview');
 await page.locator('.album-controls > summary').click();await page.getByLabel('Background material',{exact:true}).selectOption('antique');await expect(page.getByLabel('Paper age value',{exact:true})).toHaveValue('70');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('Background material',{exact:true})).toHaveValue('plain');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByLabel('Background material',{exact:true})).toHaveValue('antique');
 await page.getByLabel('Photo corner mounts',{exact:true}).selectOption('black');await page.getByRole('button',{name:'Paper edges',exact:true}).click();await page.getByRole('button',{name:'Rounded washi',exact:true}).click();await expect(page.getByLabel('Corner rounding value',{exact:true})).toHaveValue('4.5');await expect(page.locator('.status-main')).toContainText('Refined preview');
 const preview=page.getByLabel('Rendered photograph and paper',{exact:true}),revision=await preview.getAttribute('data-render-revision');await page.getByLabel('Corner rounding value',{exact:true}).fill('8');await page.getByLabel('Corner rounding value',{exact:true}).blur();await expect.poll(()=>preview.getAttribute('data-render-revision')).not.toBe(revision);
 await page.getByRole('button',{name:'Project options'}).click();await page.getByRole('button',{name:'Save on this device',exact:true}).click();await expect(page.getByRole('status')).toContainText('Saved on this device');await page.reload();await expect(page.locator('.status-main')).toContainText('Refined preview');await page.getByRole('button',{name:'Project options'}).click();await page.getByRole('button',{name:'Open saved project',exact:true}).click();await page.getByRole('button',{name:'Open',exact:true}).click();await page.locator('.album-controls > summary').click();await expect(page.getByLabel('Background material',{exact:true})).toHaveValue('antique');await expect(page.getByLabel('Photo corner mounts',{exact:true})).toHaveValue('black');await page.getByRole('button',{name:'Paper edges',exact:true}).click();await expect(page.getByLabel('Corner rounding value',{exact:true})).toHaveValue('8');
 await page.getByLabel('Background material',{exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/albums/editor-desktop.png'});
 for(const format of ['PNG','JPEG']){await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByLabel('Export width',{exact:true}).fill('1400');await page.getByLabel('Allow enlargement',{exact:false}).check();if(format==='JPEG')await page.getByRole('button',{name:'JPEG Smaller file'}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download '+format,exact:true}).click();const download=await pending,path='artifacts/albums/ui-export.'+(format==='PNG'?'png':'jpg');await download.saveAs(path);expect((await sharp(path).metadata()).width).toBe(1400);}
 await page.getByRole('button',{name:'Project options'}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download settings',exact:true}).click();const file=await pending;await file.saveAs('artifacts/albums/ui-settings.json');const saved=JSON.parse(await fs.readFile(await file.path() as string,'utf8'));expect(saved.schemaVersion).toBe(6);expect(saved.stage.material).toBe('antique');expect(saved.edges.cornerRadius).toBe(8);
 await page.setViewportSize({width:390,height:900});await page.getByLabel('Background material',{exact:true}).scrollIntoViewIfNeeded();await page.screenshot({path:'artifacts/albums/editor-mobile.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);expect(errors).toEqual([]);
});
