import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import sharp from 'sharp';
test('real local import, crop, film, undo, save, exact downloaded PNG/JPEG and responsive keyboard UI',async({page})=>{
 const errors:string[]=[],network:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>network.push(r.url()));
 await page.goto('/');await expect(page.locator('.status-main')).toContainText('Refined preview');
 await page.locator('input[aria-label="Choose photo file"]').setInputFiles('Sample/fire-night.jpg');await expect(page.locator('.main-photo-card')).toContainText('fire-night.jpg');await expect(page.locator('.status-main')).toContainText('Refined');
 await page.getByRole('button',{name:/Starting point/}).click();await page.getByRole('button',{name:'Apply Torn Sequence preset'}).click();await page.getByRole('tab',{name:/Photo$/}).click();await page.getByRole('button',{name:'Film response',exact:true}).click();await page.getByLabel('Film profile',{exact:true}).selectOption('classic-400');
 await page.getByRole('button',{name:'Black & white',exact:true}).click();await expect(page.getByLabel('Black & white value',{exact:true})).toHaveValue('100');
 await page.getByLabel('Finish strength value').fill('74');await page.getByLabel('Finish strength value').blur();await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('Finish strength value')).toHaveValue('100');await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.getByLabel('Finish strength value')).toHaveValue('74');
 await page.getByRole('tab',{name:/Compose$/}).click();await page.getByRole('button',{name:'Crop main photo',exact:true}).click();await page.getByLabel('Crop width percent').fill('90');await page.getByRole('button',{name:'Apply crop'}).click();await expect(page.locator('.status-main')).toContainText('Refined');
 await page.getByRole('button',{name:'Project options'}).click();await page.getByRole('button',{name:'Save project locally',exact:true}).click();await expect(page.getByRole('status')).toContainText('Project saved locally');
 await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByLabel('Export width',{exact:true}).fill('1200');await page.getByLabel('Transparent surroundings').check();const exportDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Download PNG',exact:true}).click();const downloaded=await exportDownload;const filename='artifacts/browser-downloaded-strips.png';await downloaded.saveAs(filename);const meta=await sharp(filename).metadata();expect(meta.width).toBe(1200);expect(meta.hasAlpha).toBe(true);await expect(page.getByRole('dialog')).not.toBeVisible();
 const performance=await page.evaluate(()=>(window as any).__lastExport);await fs.writeFile('artifacts/ui-export-metrics.json',JSON.stringify(performance,null,2));
 await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByLabel('Export view',{exact:true}).selectOption('image');await page.getByLabel('Export width',{exact:true}).fill('900');await page.getByRole('button',{name:'JPEG Smaller file'}).click();const jpegPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download JPEG',exact:true}).click();await (await jpegPromise).saveAs('artifacts/browser-downloaded-image.jpg');expect((await sharp('artifacts/browser-downloaded-image.jpg').metadata()).width).toBe(900);
 await page.getByRole('button',{name:'Project options'}).click();const settingsPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download settings',exact:true}).click();await (await settingsPromise).saveAs('artifacts/browser-settings.json');await page.getByLabel('Choose settings file').setInputFiles('artifacts/browser-settings.json');await expect(page.getByRole('status')).toContainText('Settings restored');
 await page.getByLabel('Choose photo file').setInputFiles('tests/fixtures/corrupt.png');await expect(page.getByRole('alert')).toContainText('Truncated');await expect(page.locator('.main-photo-card')).toContainText('fire-night.jpg');await page.getByRole('button',{name:'Dismiss error'}).click();
 await page.getByRole('button',{name:'Object',exact:true}).click();await expect(page.locator('.status-main')).toContainText('Refined');await page.screenshot({path:'artifacts/editor-user-sample.png'});
 await page.getByRole('tab',{name:/Photo$/}).click();await page.getByLabel('Finish strength',{exact:true}).focus();await page.keyboard.press('ArrowLeft');await expect(page.getByLabel('Finish strength value')).toHaveValue('73');
 await expect(page.locator('canvas[aria-label="Rendered photograph and paper"]')).toHaveAttribute('data-quality','refined');
 const latencies:number[]=[];
 for(let i=0;i<12;i++){const previous=await page.locator('canvas[aria-label="Rendered photograph and paper"]').getAttribute('data-render-revision');const start=Date.now();await page.keyboard.press('ArrowRight');await page.waitForFunction(old=>document.querySelector('canvas[aria-label="Rendered photograph and paper"]')?.getAttribute('data-render-revision')!==old,previous);latencies.push(Date.now()-start);}
 latencies.sort((a,b)=>a-b);await fs.writeFile('artifacts/ui-preview-latency.json',JSON.stringify({method:'Keyboard control change to displayed canvas revision; Playwright polling included',samplesMs:latencies,medianMs:latencies[6],p95Ms:latencies[11]},null,2));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/editor-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await expect(page.getByRole('button',{name:'Export',exact:true})).toBeInViewport();
 expect(errors).toEqual([]);const external=network.filter(u=>!u.startsWith('http://127.0.0.1:5173')&&!u.startsWith('blob:')&&!u.startsWith('data:'));expect(external).toEqual([]);await fs.writeFile('artifacts/network-audit.json',JSON.stringify({requests:network,externalRequests:external,pageErrors:errors},null,2));
});
