import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import sharp from 'sharp';
test('alpha, orientation pixels, ICC baseline, fallback parity, storage, cancellation, and live GPU resource stability',async({page})=>{
 await page.goto('/');await expect(page.locator('.status-main')).toContainText('Refined preview');
 const report=await page.evaluate(async()=>{
  const harnessUrl='/tests/browser/harness.ts',modelUrl='/src/model/project.ts',adapterUrl='/src/render/adapter.ts',inputUrl='/src/imaging/input.ts';
  const {Harness,difference}=await import(harnessUrl),{RenderAdapter}=await import(adapterUrl),{decodeSource}=await import(inputUrl),model=await import(modelUrl);
  const h=new Harness(),n=model.neutral(),report:any={};
  // Count real live allocations made through the renderer, not just an estimated byte formula.
  const gl=h.renderer.gl,textures=new Set(),framebuffers=new Set();const ct=gl.createTexture.bind(gl),dt=gl.deleteTexture.bind(gl),cf=gl.createFramebuffer.bind(gl),df=gl.deleteFramebuffer.bind(gl);
  gl.createTexture=()=>{const t=ct();textures.add(t);return t;};gl.deleteTexture=(t:WebGLTexture|null)=>{textures.delete(t);dt(t);};gl.createFramebuffer=()=>{const t=cf();framebuffers.add(t);return t;};gl.deleteFramebuffer=(t:WebGLFramebuffer|null)=>{framebuffers.delete(t);df(t);};
  report.allocations=[];for(let i=0;i<15;i++){await h.source(i%2?'/tests/fixtures/alpha.png':'/tests/fixtures/colour-chart.png');h.render(n,600,400,'image');report.allocations.push({textures:textures.size,framebuffers:framebuffers.size});}
  await h.source('/tests/fixtures/alpha.png');const result=h.render(n),bitmap=await createImageBitmap(await(await fetch('/tests/fixtures/alpha.png')).blob());const baseline=new OffscreenCanvas(600,400);baseline.getContext('2d')!.drawImage(bitmap,0,0);bitmap.close();const bytes=baseline.getContext('2d')!.getImageData(0,0,600,400).data;let alphaError=0,premulError=0;for(let i=0;i<bytes.length;i+=4){alphaError=Math.max(alphaError,Math.abs(bytes[i+3]-result.pixels[i+3]));for(let ch=0;ch<3;ch++)premulError=Math.max(premulError,Math.abs(bytes[i+ch]*bytes[i+3]/255-result.pixels[i+ch]*result.pixels[i+3]/255));}report.alpha={alphaError,premulError};const paper=h.render(n,600,400,'flat');report.alpha.paperPixel=paper.pixels[(120*600+170)*4+3];
  const alphaOutput=await h.output(model.initialProject(),1400,'object',true);report.alphaOutput=alphaOutput.base64;
  report.orientationPixels=[];for(const o of [1,2,6,8]){const info=await h.source(`/tests/fixtures/orientation-${o}.jpg`);const r=h.render(n,info.width,info.height,'image');const i=(10*info.width+10)*4;report.orientationPixels.push({orientation:o,rgb:Array.from(r.pixels.slice(i,i+3))});}
  await h.source('/tests/fixtures/display-p3.jpg');const icc=h.render(n,120,80,'image');const img=new Image();img.src='/tests/fixtures/display-p3.jpg';await img.decode();const ic=new OffscreenCanvas(120,80);ic.getContext('2d',{colorSpace:'srgb'})!.drawImage(img,0,0);const ib=ic.getContext('2d')!.getImageData(0,0,120,80).data;report.icc=difference(icc.pixels,ib);report.icc.interiorMax=0;for(const [ox,oy] of [[8,8],[72,8],[8,55],[88,55]])for(let y=oy;y<oy+10;y++)for(let x=ox;x<ox+12;x++)for(let ch=0;ch<3;ch++){const k=(y*120+x)*4+ch;report.icc.interiorMax=Math.max(report.icc.interiorMax,Math.abs(icc.pixels[k]-ib[k]));}
  const d=await decodeSource(await(await fetch('/tests/fixtures/colour-chart.png')).blob(),'chart');const main=new RenderAdapter(),worker=new RenderAdapter();report.main=await main.init(true);report.worker=await worker.init();await main.setSource(d.bitmap);await worker.setSource(d.bitmap);d.bitmap.close();const options={width:800,height:600,view:'object',quality:'refined',includeBackground:false,includeShadow:true};const p=model.initialProject();const [a,b]=await Promise.all([main.render(p,options),worker.render(p,options)]);const ac=new OffscreenCanvas(800,600),bc=new OffscreenCanvas(800,600);ac.getContext('2d')!.drawImage(a.bitmap,0,0);bc.getContext('2d')!.drawImage(b.bitmap,0,0);a.bitmap.close();b.bitmap.close();report.fallbackParity=difference(ac.getContext('2d')!.getImageData(0,0,800,600).data,bc.getContext('2d')!.getImageData(0,0,800,600).data,true);main.dispose();worker.dispose();
  h.renderer.dispose();report.afterDispose={textures:textures.size,framebuffers:framebuffers.size};return report;
 });
 const output=Buffer.from(report.alphaOutput,'base64');delete report.alphaOutput;await fs.writeFile('artifacts/alpha-object.png',output);for(const colour of ['#000000','#ffffff','#9f22c5'])await sharp(output).flatten({background:colour}).png().toFile(`artifacts/alpha-over-${colour.slice(1)}.png`);
 await fs.writeFile('artifacts/hardening.json',JSON.stringify(report,null,2));
 expect(report.alpha.alphaError).toBeLessThanOrEqual(1);expect(report.alpha.premulError).toBeLessThanOrEqual(2);expect(report.alpha.paperPixel).toBe(255);expect(report.icc.interiorMax).toBeLessThanOrEqual(2);expect(report.fallbackParity.max).toBeLessThanOrEqual(1);expect(report.main.adapter).toContain('Main');expect(report.worker.adapter).toContain('Worker');expect(report.allocations.every((v:any)=>JSON.stringify(v)===JSON.stringify(report.allocations[0]))).toBe(true);expect(report.afterDispose).toEqual({textures:0,framebuffers:0});
 const expected=[[225,50,34],[49,179,65],[229,213,49],[49,179,65]];report.orientationPixels.forEach((r:any,i:number)=>r.rgb.forEach((v:number,ch:number)=>expect(Math.abs(v-expected[i][ch])).toBeLessThanOrEqual(4)));
 await page.getByRole('tab',{name:/Photo$/}).click();await page.getByLabel('Finish strength value').fill('82');await page.getByLabel('Finish strength value').blur();await page.getByRole('button',{name:'Project options'}).click();await page.getByRole('button',{name:'Save project locally',exact:true}).click();await expect(page.getByRole('status')).toContainText('Project saved locally');await page.getByLabel('Finish strength value').fill('25');await page.getByLabel('Finish strength value').blur();await page.getByRole('button',{name:'Project options'}).click();await page.getByRole('button',{name:'Open saved project'}).click();await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.getByLabel('Finish strength value')).toHaveValue('82');
 const downloads:string[]=[];page.on('download',d=>downloads.push(d.suggestedFilename()));await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByLabel('Export width',{exact:true}).fill('4000');await page.getByLabel('Allow enlargement').check();await page.getByRole('button',{name:'Download PNG',exact:true}).click();await page.getByRole('button',{name:'Cancel export',exact:true}).click();await expect(page.getByRole('status')).toContainText('cancelled');expect(downloads).toEqual([]);report.cancelledDownloads=downloads.length;
 await fs.writeFile('artifacts/hardening.json',JSON.stringify(report,null,2));
});


