import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import sharp from 'sharp';
const folder='artifacts/high-resolution';
test.beforeAll(async()=>{
 await fs.mkdir(folder,{recursive:true});
 const svg=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="9504" height="6336"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#254158"/><stop offset="1" stop-color="#e0ad75"/></linearGradient><pattern id="grid" width="96" height="96" patternUnits="userSpaceOnUse"><path d="M0 48H96M48 0V96" stroke="#f4e2c0" stroke-width="2" opacity=".18"/></pattern></defs><path fill="url(#sky)" d="M0 0H9504V6336H0z"/><circle cx="7000" cy="1700" r="580" fill="#f8e6b8"/><path d="M0 4700L1800 1800L3600 4100L5500 2600L8000 5100L9504 3900V6336H0z" fill="#25332d"/><path d="M0 5500Q2200 4200 4800 5450T9504 5400V6336H0z" fill="#657d6e"/><path fill="url(#grid)" d="M0 0H9504V6336H0z"/><rect x="160" y="160" width="1700" height="300" fill="#ffffff"/><text x="220" y="365" font-size="165" fill="#203224">9504 x 6336</text><path d="M100 100H700M100 100V700M9404 6236H8804M9404 6236V5636" stroke="#f6d79d" stroke-width="24"/></svg>');
 await sharp(svg,{limitInputPixels:false}).jpeg({quality:94}).toFile(folder+'/source-60mp.jpg');
 await sharp({create:{width:3000,height:2500,channels:3,background:'#917b64'}}).png({compressionLevel:0}).toFile(folder+'/over-20mb.png');
});
test('60 MP original import, source-resolution JPEG, 30 MP paper PNG, large file and multi-photo save',async({page})=>{
 test.setTimeout(240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('/');await expect(page.locator('.status-main')).toContainText('Refined preview');
 await page.getByLabel('Choose photo file',{exact:true}).setInputFiles(folder+'/source-60mp.jpg');await expect(page.locator('.main-photo-card')).toContainText('source-60mp.jpg');await expect(page.locator('.status-main')).toContainText('Refined preview');await expect(page.getByRole('alert')).toHaveCount(0);
 await page.getByRole('button',{name:'Image only',exact:true}).click();await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('button',{name:'Use source resolution',exact:true}).click();await expect(page.getByLabel('Export width',{exact:true})).toHaveValue('9504');await expect(page.getByLabel('Export height',{exact:true})).toHaveValue('6336');await expect(page.locator('.export-size')).toContainText('graphics dimension limit');
 await page.getByRole('button',{name:'JPEG Smaller file'}).click();let pending=Promise.race([page.waitForEvent('download',{timeout:120000}),page.getByRole('alert').waitFor({state:'visible',timeout:120000}).then(async()=>{throw new Error(await page.getByRole('alert').innerText());})]);const start=Date.now();await page.getByRole('button',{name:'Download JPEG',exact:true}).click();await(await pending).saveAs(folder+'/native-60mp.jpg');const nativeMs=Date.now()-start;const native=await sharp(folder+'/native-60mp.jpg').metadata();expect([native.width,native.height]).toEqual([9504,6336]);
 await page.getByRole('button',{name:'Object',exact:true}).click();await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByLabel('Export width',{exact:true}).fill('6400');await page.getByLabel('Transparent surroundings').check();pending=Promise.race([page.waitForEvent('download',{timeout:120000}),page.getByRole('alert').waitFor({state:'visible',timeout:120000}).then(async()=>{throw new Error(await page.getByRole('alert').innerText());})]);const paperStart=Date.now();await page.getByRole('button',{name:'Download PNG',exact:true}).click();await(await pending).saveAs(folder+'/paper-over-30mp.png');const paperMs=Date.now()-paperStart,paper=await sharp(folder+'/paper-over-30mp.png').metadata();expect(paper.width).toBe(6400);expect(paper.width!*paper.height!).toBeGreaterThan(30000000);expect(paper.hasAlpha).toBe(true);const corner=await sharp(folder+'/paper-over-30mp.png').extract({left:0,top:0,width:1,height:1}).raw().toBuffer();expect(corner[3]).toBe(0);
 // A file over the old 20 MB gate remains full-sized, and narrowing the window does not reinstate a pool cap.
 const fileSize=(await fs.stat(folder+'/over-20mb.png')).size;expect(fileSize).toBeGreaterThan(20*1024*1024);await page.getByLabel('Choose photo file',{exact:true}).setInputFiles(folder+'/over-20mb.png');await expect(page.locator('.main-photo-card')).toContainText('over-20mb.png');await page.setViewportSize({width:390,height:900});await page.getByRole('button',{name:'Strips layout',exact:true}).click();await page.getByLabel('Photos in pieces',{exact:true}).selectOption('individual');await page.getByLabel('Choose photos for pieces',{exact:true}).setInputFiles(folder+'/source-60mp.jpg');await expect(page.getByRole('status')).toContainText('1 piece photo loaded');await expect(page.getByRole('alert')).toHaveCount(0);
 await page.getByLabel('Composition name').fill('Large originals');await page.getByRole('button',{name:'Save project',exact:true}).click();await expect(page.locator('.document-state')).toContainText('Saved locally');await page.reload();await expect(page.locator('.status-main')).toContainText('Refined preview');await page.getByRole('button',{name:'Project options'}).click();await page.getByRole('button',{name:'Open saved project',exact:true}).click();await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.getByLabel('Composition name')).toHaveValue('Large originals');await expect(page.locator('.piece-heading')).toContainText('source-60mp.jpg');await expect(page.locator('.status-main')).toContainText('Refined preview');await expect(page.getByRole('alert')).toHaveCount(0);
 // Hardware rejection happens from the header before a huge decode and keeps the current composition.
 const oversized=Buffer.from(await fs.readFile('tests/fixtures/colour-chart.png'));oversized.writeUInt32BE(100000,16);await page.getByLabel('Choose photo file',{exact:true}).setInputFiles({name:'beyond-gpu.png',mimeType:'image/png',buffer:oversized});await expect(page.getByRole('alert')).toContainText('graphics device supports photos');await expect(page.locator('.main-photo-card')).toContainText('over-20mb.png');await page.getByRole('button',{name:'Dismiss error'}).click();
 await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:folder+'/large-originals-editor.png'});expect(errors).toEqual([]);await fs.writeFile(folder+'/verification.json',JSON.stringify({source:[9504,6336],nativeExport:[native.width,native.height],nativeMs,paperExport:[paper.width,paper.height],paperMs,encodedFileBytes:fileSize,combinedPixels:9504*6336+3000*2500,savedRestoration:true,hardwareRejectionPreservedWork:true,errors},null,2));
});

test('block transfers match direct output across internal boundaries, alpha, paper and album',async({page})=>{
 await page.goto('/');await expect(page.locator('.status-main')).toContainText('Refined preview');
 const report=await page.evaluate(async()=>{const url='/tests/browser/harness.ts';const {Harness,difference}=await import(url);const h=new Harness();await h.source('/tests/fixtures/alpha.png');const results=[];
 try{for(const view of ['image','flat','object']){const p=h.initialProject();p.stage.material='antique';p.stage.mounts='black';p.edges.cornerRadius=4;p.wrinkles.enabled=true;p.wrinkles.strength=45;h.renderer.largeSurface=()=>false;h.renderer.albumKey='';const direct=h.render(p,3600,2400,view,true);h.renderer.largeSurface=()=>true;h.renderer.albumKey='';const blocked=h.render(p,3600,2400,view,true);results.push({view,...difference(direct.pixels,blocked.pixels,true)});}
 // The background pass uses its own target and must also preserve orientation.
 const p=h.initialProject();p.stage.material='antique';h.renderer.largeSurface=()=>false;h.renderer.albumKey='';const direct=h.render(p,3600,2400,'object',false);h.renderer.largeSurface=()=>true;h.renderer.albumKey='';const blocked=h.render(p,3600,2400,'object',false);results.push({view:'album',...difference(direct.pixels,blocked.pixels,true)});return results;}finally{h.renderer.dispose();}
 });
 for(const result of report)expect(result.max,result.view+' block-transfer parity').toBeLessThanOrEqual(1);await fs.writeFile(folder+'/block-parity.json',JSON.stringify(report,null,2));
});
