import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import sharp from 'sharp';
test('export every supplied sample, reference-directed recipes, profile atlases and measured large renders',async({page})=>{
 test.setTimeout(180000);await fs.mkdir('artifacts/sample-exports',{recursive:true});await fs.mkdir('artifacts/profile-atlases',{recursive:true});
 await page.goto('/');await expect(page.locator('.status-main')).toContainText('Refined preview');
 await page.evaluate(async()=>{const url='/tests/browser/harness.ts';(window as any).h=new (await import(url)).Harness();});
 const samples=(await fs.readdir('Sample').catch((error:NodeJS.ErrnoException)=>{if(error.code==='ENOENT')return [];throw error;})).filter(f=>/\.jpg$/i.test(f));const report:any={samples:[],atlases:[],performance:{}};
 for(let i=0;i<samples.length;i++){
  const data=await page.evaluate(async({name,index})=>{const h=(window as any).h;await h.source(`/Sample/${encodeURIComponent(name)}`);let p=h.clone(h.presets[index===1?0:index===5?3:2]);p=h.loadFilm(p,index===1?'fine-classic-125':'classic-400');p.bw.strength=100;p.finishStrength=100;p.tone.warmth=2;p.tone.exposureEv=name==='dying-sun.jpg'?.35:name==='Main-8547.jpg'?.1:0;p.tone.blackLift=4;p.grain.strength=18;p.paper.strength=85;p.paper.tooth=40;p.paper.fibres=36;p.paper.mottling=18;p.paper.colour='#F2F0E7';p.edges.strength=90;p.edges.irregularity=50;p.edges.roughness=65;p.edges.featherWidth=45;p.edges.looseFibres=42;p.lighting.strength=65;p.lighting.relief=45;p.lighting.shadowOpacity=32;p.lighting.elevation=14;p.stage.colour=index===1?'#191a18':'#EEEDE7';p.stage.paddingPct=5;p.layout.tearAmount=88;p.layout.gapPct=2.2;p.layout.toneVariation=index===5?30:0;
   if(index===1){p.composition.borderPct=4;p.layout.mode='single';}if(index===5){p.layout.mode='grid';p.layout.rows=4;p.layout.columns=3;p.layout.gapPct=1.1;p.layout.tearAmount=35;}p.source={id:'user-sample',displayName:name,fingerprint:null};const result=await h.output(p,2000,'object');return {result,recipe:p};},{name:samples[i],index:i});
  const stem=samples[i].replace(/\.jpg$/i,'');await fs.writeFile(`artifacts/sample-exports/${stem}-handmade.png`,Buffer.from(data.result.base64,'base64'));await fs.writeFile(`artifacts/sample-exports/${stem}-settings.json`,JSON.stringify(data.recipe,null,2));report.samples.push({file:samples[i],width:data.result.width,height:data.result.height,ms:data.result.ms,metrics:data.result.metrics});
 }
 // Same photograph and recipe in all three export branches; files can be opened directly.
 const branchSource=samples.includes('fire-night.jpg')?'/Sample/fire-night.jpg':'/samples/mountain-lake.jpg';
 const branchData=await page.evaluate(async(source)=>{const h=(window as any).h;await h.source(source);const p=h.clone(h.presets[2]);p.paper.strength=85;p.paper.tooth=60;p.lighting.strength=90;p.lighting.relief=80;const out=[];for(const view of ['object','flat','image'])out.push({view,...await h.output(p,1800,view,true)});return out;},branchSource);
 for(const out of branchData)await fs.writeFile(`artifacts/sample-exports/three-views-${out.view}.png`,Buffer.from(out.base64,'base64'));
 // Real exported atlas cells: all 14 profiles across a chart, synthetic portrait, daylight and night.
 for(const fixture of ['colour-chart','portrait','daylight','night']){
  const cells=await page.evaluate(async(fixture)=>{const h=(window as any).h;await h.source(fixture==='daylight'?'/samples/mountain-lake.jpg':`/tests/fixtures/${fixture}.png`);const results=[];for(const film of h.films){let p=h.loadFilm(h.neutral(),film.id);const normal=await h.output(p,420,'image');p.grain.strength=0;const clean=await h.output(p,420,'image');results.push({id:film.id,name:film.name,normal:normal.base64,clean:clean.base64});}return results;},fixture);
  for(const kind of ['normal','clean'] as const){const layers:any[]=[];for(let i=0;i<cells.length;i++){const cell=cells[i];const thumb=await sharp(Buffer.from(cell[kind],'base64')).resize(300,200,{fit:'cover'}).png().toBuffer();layers.push({input:thumb,left:(i%4)*320+10,top:Math.floor(i/4)*240+10});layers.push({input:Buffer.from(`<svg width="310" height="27"><text x="4" y="19" font-size="12" font-family="Arial" fill="#323b2e">${cell.name}</text></svg>`),left:(i%4)*320+8,top:Math.floor(i/4)*240+212});}await sharp({create:{width:1280,height:960,channels:3,background:'#ebece6'}}).composite(layers).jpeg({quality:94}).toFile(`artifacts/profile-atlases/${fixture}-${kind}.jpg`);}
  report.atlases.push({fixture,profiles:cells.length,variants:['with-grain','grain-off']});
 }
 const perf=await page.evaluate(async()=>{const h=(window as any).h;const start=performance.now();await h.source('/tests/fixtures/large-12mp.jpg');let p=h.initialProject();let first=h.render(p,1200,900,'object');await createImageBitmap(first.canvas).then(b=>b.close());const firstMs=performance.now()-start;const times=[];for(let i=0;i<30;i++){p.tone.exposureEv=i*.01;const t=performance.now();const r=h.render(p,1200,900,'object');await createImageBitmap(r.canvas).then(b=>b.close());times.push(performance.now()-t);}const large=[];for(const mode of ['single','grid']){p.layout.mode=mode;p.layout.rows=6;p.layout.columns=6;const t=performance.now();const result=await h.renderer.encode(p,{width:4000,height:3000,quality:'export',view:'object',includeBackground:true,includeShadow:true},'image/png',1);large.push({mode,ms:performance.now()-t,bytes:result.blob.size,estimatedBytes:result.metrics.estimatedBytes});}const replacements=[];for(let i=0;i<12;i++){await h.source(i%2?'/tests/fixtures/colour-chart.png':'/tests/fixtures/grey.png');const r=h.render(h.initialProject(),900,600,'object');replacements.push(r.metrics.estimatedBytes);}times.sort((a,b)=>a-b);return {first12mpPreviewMs:firstMs,interactiveMedianMs:times[Math.floor(times.length/2)],interactiveP95Ms:times[Math.floor(times.length*.95)],large,replacements,browser:navigator.userAgent,gpu:h.renderer.capability.gpu};});report.performance=perf;
 expect(perf.replacements.at(-1)).toBe(perf.replacements[0]);await fs.writeFile('artifacts/reference-and-performance.json',JSON.stringify(report,null,2));
});
