import {test,expect} from '@playwright/test';
import fs from 'node:fs/promises';
import sharp from 'sharp';
test('canonical renderer: neutral, B&W, halos, grain, profiles, materials, geometry, versions and export parity',async({page})=>{
 await page.goto('/');await expect(page.locator('.status-main')).toContainText('Refined preview');
 await page.evaluate(async()=>{const url='/tests/browser/harness.ts';const module=await import(url);(window as any).h=new module.Harness();(window as any).diff=module.difference;});
 const report=await page.evaluate(async()=>{
  const h=(window as any).h,diff=(window as any).diff;const report:any={capability:h.renderer.capability};
  await h.source('/tests/fixtures/colour-chart.png');const n=h.neutral();const a=h.render(n);const image=await createImageBitmap(await (await fetch('/tests/fixtures/colour-chart.png')).blob());const c=new OffscreenCanvas(600,400);c.getContext('2d')!.drawImage(image,0,0);const source=c.getContext('2d')!.getImageData(0,0,600,400).data;image.close();report.neutral=diff(a.pixels,source);
  const hashes:string[]=[];const bytesHash=(data:Uint8ClampedArray)=>{let v=2166136261;for(const c of data)v=Math.imul(v^c,16777619);return (v>>>0).toString(16);};
  report.profiles=[];for(const f of h.films){const p=h.loadFilm(n,f.id);p.grain.strength=0;const r=h.render(p);hashes.push(bytesHash(r.pixels));let channelError=0;for(let i=0;i<r.pixels.length;i+=4)channelError=Math.max(channelError,Math.abs(r.pixels[i]-r.pixels[i+1]),Math.abs(r.pixels[i+1]-r.pixels[i+2]));report.profiles.push({id:f.id,hash:hashes.at(-1),neutralBwChannelError:f.family==='bw'?channelError:null});}report.distinctProfiles=new Set(hashes).size;
  const bw=h.loadFilm(n,'classic-400');bw.grain.chroma=100;bw.grain.strength=90;const b=h.render(bw);let eq=0;for(let i=0;i<b.pixels.length;i+=4)eq=Math.max(eq,Math.abs(b.pixels[i]-b.pixels[i+1]),Math.abs(b.pixels[i]-b.pixels[i+2]));report.bwChannelError=eq;
  bw.grain.strength=0;bw.film.strength=0;const base=h.render(bw).pixels;bw.bw.filter='red';bw.bw.mixer.blue=-70;const filtered=h.render(bw).pixels;const pos=(x:number,y:number)=>4*(y*600+x);report.filter={red:filtered[pos(50,50)]-base[pos(50,50)],blue:filtered[pos(450,50)]-base[pos(450,50)],neutral:filtered[pos(450,200)]-base[pos(450,200)]};
  const active=h.loadFilm(h.initialProject(),'classic-400');active.film.strength=0;const before=h.render(active).pixels;active.grain.strength=0;report.independentGrain=diff(before,h.render(active).pixels).mean;active.finishStrength=0;report.finishZero=diff(a.pixels,h.render(active).pixels);
  await h.source('/tests/fixtures/grey.png');const grain=h.neutral();grain.grain.strength=70;grain.grain.enabled=true;grain.grain.size=45;const g=h.render(grain).pixels;const stats=(v:Uint8ClampedArray)=>{let s=0,ss=0,n=0,grad=0;for(let y=8;y<392;y++)for(let x=8;x<592;x++){const i=(y*600+x)*4;let n0=v[i];s+=n0;ss+=n0*n0;n++;grad+=Math.abs(n0-v[i+4]);}return {mean:s/n,sd:Math.sqrt(ss/n-(s/n)**2),gradient:grad/n};};report.grain={normal:stats(g)};grain.grain.format='large';report.grain.large=stats(h.render(grain).pixels);
  const halo=h.neutral();halo.film.enabled=true;halo.film.strength=100;halo.film.halation=100;halo.film.halationRadius=100;report.greyHalo=diff(h.render(halo).pixels,h.render(h.neutral()).pixels);await h.source('/tests/fixtures/night.png');const nh=h.render(halo).pixels;halo.film.halation=0;const clean=h.render(halo).pixels;halo.film.bloom=100;const bloom=h.render(halo).pixels;report.halo={difference:diff(nh,clean).mean,redRing:nh[pos(320,190)]-clean[pos(320,190)],bloomDifference:diff(bloom,clean).mean};
  await h.source('/tests/fixtures/grey.png');const paper=h.loadMaterial(h.neutral(),'cold-press');paper.paper.strength=100;paper.paper.tooth=80;paper.lighting.strength=100;paper.lighting.relief=80;paper.lighting.shadowOpacity=60;paper.lighting.enabled=true;const front=h.render(paper,800,600,'object').pixels;paper.lighting.azimuthDeg=(paper.lighting.azimuthDeg+180)%360;report.relight=diff(front,h.render(paper,800,600,'object').pixels);const flat=h.render(paper,800,600,'flat').pixels;paper.lighting.azimuthDeg=20;report.flatLightInvariant=diff(flat,h.render(paper,800,600,'flat').pixels);report.materials=[];for(const m of h.materials){const p=h.loadMaterial(paper,m.id);const r=h.render(p,800,600,'object');report.materials.push({id:m.id,hash:bytesHash(r.pixels),dry:p.ink.coverageLoss});}
  const manifest=await h.maps();const mapped=h.loadMaterial(paper,'smooth');mapped.paper.assetId=manifest.id;mapped.paper.assetVersion=manifest.version;mapped.paper.assetMix=100;mapped.paper.tooth=80;const mapped1=h.render(mapped,800,600,'object');mapped.lighting.azimuthDeg+=180;report.mapRelight=diff(mapped1.pixels,h.render(mapped,800,600,'object').pixels);mapped.paper.assetId='missing';report.missingAsset=h.render(mapped,800,600,'object').metrics.warnings;
  await h.source('/tests/fixtures/checkerboard.png');const neutral=h.neutral();neutral.stage.background='transparent';neutral.layout.gapPct=0;const one=h.render(neutral,900,700,'flat');neutral.layout.mode='grid';const grid=h.render(neutral,900,700,'flat');report.zeroGap=diff(one.pixels,grid.pixels,true);
  const p=h.initialProject();p.finishStrength=0;const lo=h.render(p,600,400,'flat'),hi=h.render(p,1800,1200,'flat');const down=new OffscreenCanvas(600,400);const ctx=down.getContext('2d')!;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(hi.canvas,0,0,600,400);report.previewParity=diff(lo.pixels,ctx.getImageData(0,0,600,400).data,true);
  const extreme=h.initialProject();extreme.edges.strength=100;extreme.edges.irregularity=100;extreme.edges.looseFibres=100;extreme.lighting.strength=100;extreme.lighting.elevation=100;extreme.lighting.altitudeDeg=15;extreme.lighting.shadowOpacity=100;extreme.stage.paddingPct=0;extreme.layout.mode='grid';extreme.layout.scatter=100;const ext=h.render(extreme,900,700,'object');let outerAlpha=0;for(let x=0;x<900;x++)outerAlpha=Math.max(outerAlpha,ext.pixels[x*4+3],ext.pixels[((699)*900+x)*4+3]);for(let y=0;y<700;y++)outerAlpha=Math.max(outerAlpha,ext.pixels[(y*900)*4+3],ext.pixels[(y*900+899)*4+3]);report.boundsOuterAlpha=outerAlpha;
  report.orientations=[];for(const o of [1,2,6,8]){const info=await h.source(`/tests/fixtures/orientation-${o}.jpg`);report.orientations.push({orientation:o,width:info.width,height:info.height});}
  return report;
 });
 await fs.writeFile('artifacts/render-acceptance.json',JSON.stringify(report,null,2));
 expect(report.neutral.max).toBeLessThanOrEqual(2);expect(report.distinctProfiles).toBe(14);expect(report.bwChannelError).toBeLessThanOrEqual(1);expect(report.filter.red).toBeGreaterThan(0);expect(report.filter.blue).toBeLessThan(0);expect(report.filter.neutral).toBe(0);expect(report.independentGrain).toBeGreaterThan(.02);expect(report.finishZero.max).toBeLessThanOrEqual(2);expect(Math.abs(report.grain.normal.mean-136)).toBeLessThan(1);expect(report.grain.normal.sd).toBeGreaterThan(report.grain.large.sd);expect(report.greyHalo.max).toBe(0);expect(report.halo.difference).toBeGreaterThan(.01);expect(report.halo.bloomDifference).toBeGreaterThan(.01);expect(report.relight.mean).toBeGreaterThan(.05);expect(report.flatLightInvariant.max).toBe(0);expect(new Set(report.materials.map((m:any)=>m.hash)).size).toBe(7);expect(report.mapRelight.mean).toBeGreaterThan(.1);expect(report.missingAsset[0]).toContain('fallback');expect(report.zeroGap.mean).toBeLessThan(1);expect(report.previewParity.mean).toBeLessThan(2);expect(report.boundsOuterAlpha).toBeLessThanOrEqual(1);expect(report.orientations.map((x:any)=>[x.width,x.height])).toEqual([[120,80],[120,80],[80,120],[80,120]]);
 // Actual files, at full requested resolution, use the same canonical path as the UI.
 const output=await page.evaluate(async()=>{const h=(window as any).h;await h.source('/samples/mountain-lake.jpg');const p=h.initialProject();return h.output(p,1800,'object');});await fs.writeFile('artifacts/quiet-paper.png',Buffer.from(output.base64,'base64'));expect((await sharp('artifacts/quiet-paper.png').metadata()).width).toBe(output.width);
});

