import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
import sharp from 'sharp';
const stage=(page:Page,name:string)=>page.getByRole('tab',{name:new RegExp(name+'$')}).click();
const ready=(page:Page)=>expect(page.locator('.status-main')).toContainText('Refined preview');
test('piece selection follows the transformed canvas; scope and named save state persist',async({page})=>{
 await page.goto('/');await ready(page);await page.getByLabel('Composition name').fill('Three quiet moments');
 await page.getByRole('button',{name:'Strips layout',exact:true}).click();await page.getByLabel('Photos in pieces',{exact:true}).selectOption('individual');await page.getByRole('button',{name:'Make a portrait triptych',exact:true}).click();
 await page.getByLabel('Choose photos for pieces',{exact:true}).setInputFiles(['tests/fixtures/colour-chart.png','tests/fixtures/portrait.png','tests/fixtures/night.png']);await expect(page.getByRole('status')).toContainText('3 piece photos loaded');await page.getByRole('button',{name:'Gentle stagger',exact:true}).click();await ready(page);
 const piece=page.locator('.piece-overlay g').nth(1),box=(await piece.locator('polygon').boundingBox())!;await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await expect(page.getByRole('button',{name:'Select Strip 2',exact:true})).toHaveAttribute('aria-pressed','true');await expect(piece).toHaveAttribute('data-selected','true');await expect(page.locator('.piece-heading')).toContainText('Editing strip 2 only');
 await page.getByRole('button',{name:'Save project',exact:true}).click();await expect(page.locator('.document-state')).toContainText('3 photos');await expect(page.locator('.document-state')).toContainText('Saved locally');
 await stage(page,'Paper');await page.getByLabel('Image border value').fill('4');await page.getByLabel('Image border value').blur();await expect(page.locator('.document-state')).toContainText('Unsaved changes');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.document-state')).toContainText('Saved locally');await stage(page,'Photo');await expect(page.locator('.scope-label')).toHaveText('Applies to all photos');
 await page.reload();await ready(page);await page.getByRole('button',{name:'Project options'}).click();await page.getByRole('button',{name:'Open saved project',exact:true}).click();await page.getByRole('button',{name:'Open',exact:true}).click();await expect(page.getByLabel('Composition name')).toHaveValue('Three quiet moments');await expect(page.locator('.document-state')).toContainText('Saved locally');await ready(page);await page.screenshot({path:'artifacts/ui-refinement/desktop-pieces.png'});
 await page.getByRole('button',{name:'Pan canvas',exact:true}).click();const viewport=(await page.getByRole('group',{name:'Canvas zoom and pan'}).boundingBox())!;const before=await page.locator('.canvas-mount').getAttribute('style');await page.mouse.move(viewport.x+viewport.width/2,viewport.y+viewport.height/2);await page.mouse.down();await page.mouse.move(viewport.x+viewport.width/2+30,viewport.y+viewport.height/2+20);await page.mouse.up();expect(await page.locator('.canvas-mount').getAttribute('style')).not.toBe(before);await expect(page.locator('.document-state')).toContainText('Saved locally');
});
test('mobile inspector scroll keeps the print and named actions visible',async({page})=>{
 await page.setViewportSize({width:390,height:900});await page.goto('/');await ready(page);await page.getByRole('button',{name:'Strips layout',exact:true}).click();await stage(page,'Paper');await page.getByRole('button',{name:'Paper edges',exact:true}).click();const edges=page.locator('.effect-group').filter({has:page.getByRole('button',{name:'Paper edges',exact:true})});await edges.locator('.advanced summary').click();await page.getByLabel('Fibre length value',{exact:true}).scrollIntoViewIfNeeded();
 const viewport=page.getByRole('group',{name:'Canvas zoom and pan'}),before=(await viewport.boundingBox())!;expect(before.y).toBeGreaterThan(90);expect(before.height).toBeGreaterThan(120);await expect(viewport).toBeInViewport();await page.getByLabel('Fibre length value',{exact:true}).fill('90');await page.getByLabel('Fibre length value',{exact:true}).blur();await ready(page);expect((await viewport.boundingBox())!.y).toBe(before.y);expect(await page.evaluate(()=>window.scrollY)).toBe(0);await expect(page.getByRole('button',{name:'Choose photo',exact:true})).toBeInViewport();await expect(page.getByRole('button',{name:'Select pieces',exact:true})).toBeInViewport();await page.screenshot({path:'artifacts/ui-refinement/mobile-edge-controls.png'});
 await page.getByRole('button',{name:'Resize preview'}).click();expect((await viewport.boundingBox())!.height).toBeGreaterThan(before.height+60);for(const width of [320,390,768]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);await expect(page.getByRole('button',{name:'Export',exact:true})).toBeInViewport();}
});
test('export thumbnail follows transparency, album mounts, flat view and real downloads',async({page})=>{
 await page.goto('/');await ready(page);await stage(page,'Presentation');await page.getByLabel('Background material',{exact:true}).selectOption('antique');await page.getByLabel('Photo corner mounts',{exact:true}).selectOption('black');await page.getByRole('button',{name:'Export',exact:true}).click();await expect(page.getByRole('heading',{name:'Export image'})).toBeVisible();await page.getByLabel('Export width',{exact:true}).fill('640');
 const canvas=page.getByLabel('Export output preview',{exact:true});const alpha=()=>canvas.evaluate((c:HTMLCanvasElement)=>c.getContext('2d')!.getImageData(0,0,1,1).data[3]);await expect(canvas).toHaveAttribute('data-ready','true');await expect.poll(alpha).toBe(255);await page.getByLabel('Transparent surroundings').check();await expect.poll(alpha).toBe(0);await expect(page.getByText('Album paper and mounts will be omitted.')).toBeVisible();await page.screenshot({path:'artifacts/ui-refinement/export-transparent.png'});
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download PNG',exact:true}).click();await(await download).saveAs('artifacts/ui-refinement/transparent-output.png');const pixels=await sharp('artifacts/ui-refinement/transparent-output.png').ensureAlpha().raw().toBuffer({resolveWithObject:true});expect(pixels.info.width).toBe(640);expect(pixels.data[3]).toBe(0);
 await page.getByRole('button',{name:'Flat print',exact:true}).click();await page.getByRole('button',{name:'Export',exact:true}).click();await expect(page.getByLabel('Export view',{exact:true})).toHaveValue('flat');await page.getByLabel('Export width',{exact:true}).fill('640');await page.getByRole('button',{name:'JPEG Smaller file'}).click();await expect.poll(alpha).toBe(255);const jpeg=page.waitForEvent('download');await page.getByRole('button',{name:'Download JPEG',exact:true}).click();await(await jpeg).saveAs('artifacts/ui-refinement/album-flat-output.jpg');expect((await sharp('artifacts/ui-refinement/album-flat-output.jpg').metadata()).width).toBe(640);
});
test('film and paper browsers render current-photo previews and apply undoable choices',async({page})=>{
 await page.goto('/');await ready(page);await stage(page,'Photo');await page.getByRole('button',{name:'Film response',exact:true}).click();await page.getByRole('button',{name:'Browse film on your photo'}).click();const cards=page.locator('.look-card');await expect(cards).toHaveCount(15);await expect(cards.first().locator('img')).toBeVisible();await expect(cards.nth(2).locator('img')).toBeVisible();await page.screenshot({path:'artifacts/ui-refinement/film-browser.png'});await page.getByRole('button',{name:'Use Neutral',exact:true}).click();await expect(page.getByLabel('Enable Film response',{exact:true})).not.toBeChecked();await page.getByRole('button',{name:'Undo',exact:true}).click();
 await stage(page,'Paper');await page.getByRole('button',{name:'Browse paper previews'}).click();await expect(page.locator('.look-card')).toHaveCount(7);await expect(page.locator('.look-detail img').first()).toBeVisible();await expect(page.locator('.look-card').nth(3).locator('.look-photo img')).toBeVisible();await page.screenshot({path:'artifacts/ui-refinement/paper-browser.png'});await page.getByRole('button',{name:'Use Cotton Rag',exact:true}).click();await expect(page.getByLabel('Paper type',{exact:true})).toHaveValue('cotton');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.getByLabel('Paper type',{exact:true})).toHaveValue('soft-kozo');
});
