import type {Project,View} from '../model/project';
import {pieceEdit} from '../model/pieces';
import {buildGeometry,cropAspect,imagePlacement,pieceImagePlacement} from '../layout/geometry';
import type {Capability} from '../render/renderer';
export interface ExportSettings {view:View;format:'png'|'jpeg';width:number;height:number;transparent:boolean;shadow:boolean;colour:string;quality:number;allowEnlargement:boolean;}
export function outputAspect(p:Project,w:number,h:number,view:View){if(view==='image')return cropAspect(p,w,h);const g=buildGeometry(p,w,h);return g.stageWidth/g.stageHeight;}
export function defaultExport(p:Project,w:number,h:number):ExportSettings{const view=p.output.view as View,aspect=outputAspect(p,w,h,view);const long=Math.min(2400,Math.max(w*p.composition.crop.width,h*p.composition.crop.height));return {view,format:'png',width:Math.round(aspect>=1?long:long*aspect),height:Math.round(aspect>=1?long/aspect:long),transparent:p.stage.background==='transparent',shadow:true,colour:p.stage.colour,quality:.94,allowEnlargement:false};}
export function enlargementFactor(p:Project,s:ExportSettings,w:number,h:number){const cw=w*p.composition.crop.width,ch=h*p.composition.crop.height;if(s.view==='image')return Math.max(s.width/cw,s.height/ch);const g=buildGeometry(p,w,h),place=imagePlacement(p,w,h,g.width,g.height),scale=Math.min(s.width/g.stageWidth,s.height/g.stageHeight);if(p.layout.photoMode==='individual'&&p.layout.mode!=='single'){return Math.max(...g.pieces.map(piece=>{const e=pieceEdit(p,piece.id),sw=e.source?.width??w,sh=e.source?.height??h,pos=pieceImagePlacement(p,piece,sw,sh);return Math.max(pos.width*scale/(sw*pos.crop.width),pos.height*scale/(sh*pos.crop.height));}));}return Math.max(place.width*scale/cw,place.height*scale/ch);}
export function validateExport(p:Project,s:ExportSettings,w:number,h:number,c:Capability){if(!Number.isInteger(s.width)||!Number.isInteger(s.height)||s.width<16||s.height<16)throw new Error('Enter whole-number dimensions of at least 16 pixels.');if(Math.max(s.width,s.height)>c.maxSide||s.width*s.height>c.maxPixels)throw new Error(`This graphics device supports exports up to ${c.maxSide.toLocaleString()} pixels per side. No automatic resizing is applied.`);if(s.view==='image'&&Math.abs(s.width/s.height-cropAspect(p,w,h))>Math.max(2/s.height,cropAspect(p,w,h)*.002))throw new Error('Image-only export must keep the source crop proportions.');if(enlargementFactor(p,s,w,h)>1.015&&!s.allowEnlargement)throw new Error('This size enlarges the photograph. Choose a smaller size or enable Allow enlargement.');}
export function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
export function downloadJSON(data:unknown,name:string){download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),name);}

/** Keep the most constrained active crop at its original sampling density. */
export function sourceResolution(p:Project,s:ExportSettings,w:number,h:number){const basis=Number.isFinite(s.width)&&Number.isFinite(s.height)&&s.width>0&&s.height>0?s:{...defaultExport(p,w,h),view:s.view,width:2400,height:Math.max(16,Math.round(2400/outputAspect(p,w,h,s.view)))};const factor=enlargementFactor(p,basis,w,h);return {width:Math.max(16,Math.floor(basis.width/factor)),height:Math.max(16,Math.floor(basis.height/factor))};}
