import {describe,it,expect} from 'vitest';
import {neutral,initialProject,loadFilm,loadMaterial,applyCrumpledPaper,importRecipe,validateProject,presets,applyPreset,controls} from '../src/model/project';
import {films,materials} from '../src/model/profiles';
import {buildGeometry,partitionAxes} from '../src/layout/geometry';
import {noise} from '../src/imaging/random';
import {History} from '../src/model/history';
import {inspectHeader} from '../src/imaging/input';
import fs from 'node:fs';
describe('Versioned recipes and independence',()=>{
 it('migrates schema 2 with crease defaults and preserves deliberate image softness',()=>{const p=initialProject() as any;p.schemaVersion=2;p.rendererVersion='0.2.0';delete p.wrinkles.style;delete p.wrinkles.definition;p.tone.detailSoftness=27;p.ink.spread=19;const restored=importRecipe(JSON.stringify(p));expect(restored.project.schemaVersion).toBe(5);expect(restored.project.wrinkles.style).toBe('creased');expect(restored.project.wrinkles.definition).toBe(55);expect(restored.project.tone.detailSoftness).toBe(27);expect(restored.project.ink.spread).toBe(19);expect(restored.notes.join(' ')).toContain('Migrated schema 2 to 3');expect(restored.project.tone).not.toHaveProperty('sharpness');const invalid=neutral();invalid.wrinkles.style='unknown';expect(()=>validateProject(invalid)).toThrow();invalid.wrinkles.style='crumpled';invalid.wrinkles.definition=101;expect(()=>validateProject(invalid)).toThrow();});
 it('crumpled material recipe keeps photo, film, tone and layout while enabling raking light',()=>{const p=loadFilm(initialProject(),'classic-400');p.composition.crop={x:.1,y:.1,width:.8,height:.8};p.tone.detailSoftness=17;const q=applyCrumpledPaper(p);validateProject(q);for(const key of ['source','film','tone','bw','grain','composition','layout','edges','stage'] as const)expect(q[key]).toEqual(p[key]);expect(q.wrinkles.style).toBe('crumpled');expect(q.wrinkles.seed).toBe(p.wrinkles.seed);expect(q.lighting.enabled).toBe(true);expect(q.lighting.relief).toBeGreaterThan(0);expect(q.ink.spread).toBe(0);});
 it('validates every preset, film, and material recipe',()=>{expect(presets).toHaveLength(6);expect(films).toHaveLength(14);expect(materials).toHaveLength(7);presets.forEach(validateProject);films.forEach(f=>validateProject(loadFilm(neutral(),f.id)));materials.forEach(m=>validateProject(loadMaterial(neutral(),m.id)));expect(new Set(films.map(f=>f.hash)).size).toBe(14);});
 it('film selection preserves composition, tone, paper and all independent seeds',()=>{const p=initialProject();p.composition.crop={x:.1,y:.2,width:.8,height:.6};const f=loadFilm(p,'tungsten-night');for(const k of ['composition','paper','layout','tone','edges','lighting'] as const)expect(f[k]).toEqual(p[k]);expect(f.grain.seed).toBe(p.grain.seed);expect(f.bw.strength).toBe(0);const none=loadFilm(f,'none');expect(none.grain).toEqual(f.grain);expect(none.film.halation).toBe(30);});
 it('material preserves film, crop, edges, lighting and latent wrinkles',()=>{const p=loadFilm(initialProject(),'classic-400');p.wrinkles.strength=23;const q=loadMaterial(p,'baryta');expect(q.film).toEqual(p.film);expect(q.edges).toEqual(p.edges);expect(q.wrinkles).toEqual(p.wrinkles);expect(q.ink.coverageLoss).toBe(0);expect(loadMaterial(q,'creased-kozo').wrinkles.strength).toBe(35);});
 it('migrates schema 1 monochrome once and rejects newer/invalid settings',()=>{const p=neutral() as unknown as Record<string,unknown>;p.schemaVersion=1;delete p.film;delete p.bw;(p.tone as Record<string,unknown>).monochrome=80;(p.tone as Record<string,unknown>).strength=50;const result=importRecipe(JSON.stringify(p));expect(result.project.bw.strength).toBe(40);expect(result.notes[0]).toContain('Migrated');expect('monochrome' in result.project.tone).toBe(false);expect(()=>importRecipe('{"schemaVersion":6}')).toThrow('Unsupported');expect(()=>importRecipe('x'.repeat(270000))).toThrow('256 KB');const bad=neutral();bad.grain.strength=101;expect(()=>validateProject(bad)).toThrow();const extra={...neutral(),externalURL:'https://example.com'};expect(()=>validateProject(extra)).toThrow();});
 it('preserves requested layout when applying presets without layout',()=>{const p=neutral();p.layout.mode='grid';p.composition.borderPct=11;p.composition.crop.width=.7;const q=applyPreset(p,2,false);expect(q.composition).toEqual(p.composition);expect(q.layout).toEqual(p.layout);});
 it('one drag is one undo action with a bounded history',()=>{const h=new History(),p=neutral(),q=structuredClone(p);h.begin(p);q.paper.strength=75;h.commit(p,q);expect(h.past).toHaveLength(1);expect(h.undo(q)).toEqual(p);expect(h.redo(p)).toEqual(q);for(let i=0;i<110;i++){const n=structuredClone(q);n.grain.seed=i;h.commit(q,n);}expect(h.past).toHaveLength(100);});
 it('has complete numerical-control audit fields',()=>{expect(controls.length).toBeGreaterThan(75);controls.forEach(c=>{expect(c.min).toBeLessThan(c.max);expect(c.invalidates.length).toBeGreaterThan(0);expect(c.fixture).toBeTruthy();expect(c.conversion).toBeTruthy();});});
});
describe('Continuous, deterministic layout',()=>{
 it('all partitions cover a numbered checkerboard once',()=>{for(const mode of ['single','strips','grid']){const p=neutral();p.layout.mode=mode;const g=buildGeometry(p,600,400);expect(g.pieces.reduce((s,p)=>s+p.width*p.height,0)).toBeCloseTo(g.width*g.height,5);for(let y=5;y<g.height;y+=11)for(let x=5;x<g.width;x+=13)expect(g.pieces.filter(p=>x>=p.x&&x<p.x+p.width&&y>=p.y&&y<p.y+p.height)).toHaveLength(1);}});
 it('gaps translate pieces without changing source partitions or tear paths',()=>{const p=presets[2],before=buildGeometry(p,600,400);const q=structuredClone(p);q.layout.gapPct=6;const after=buildGeometry(q,600,400);before.pieces.forEach((v,i)=>{expect(v.points).toEqual(after.pieces[i].points);expect([v.x,v.y,v.width,v.height]).toEqual([after.pieces[i].x,after.pieces[i].y,after.pieces[i].width,after.pieces[i].height]);});expect(after.pieces[1].dy).not.toBe(before.pieces[1].dy);});
 it('unrelated controls do not change material/contour seeds or geometry',()=>{const p=initialProject(),g=buildGeometry(p,600,400),sample=noise(12.23,45.67,p.paper.seed);p.tone.exposureEv=1.2;p.lighting.azimuthDeg=100;expect(buildGeometry(p,600,400)).toEqual(g);expect(noise(12.23,45.67,p.paper.seed)).toBe(sample);});
 it('grid variation has weighted zero mean and independent placement',()=>{const p=presets[3],g=buildGeometry(p,600,400);expect(g.pieces.reduce((s,v)=>s+v.tone*v.width*v.height,0)).toBeCloseTo(0,6);const q=structuredClone(p);q.layout.toneVariation=100;expect(buildGeometry(q,600,400).pieces.map(x=>[x.dx,x.dy,x.angle])).toEqual(g.pieces.map(x=>[x.dx,x.dy,x.angle]));});
 it('rejects unordered, inconsistent and out-of-bounds crops',()=>{const p=neutral();p.layout.cutPositions=[.8,.2];expect(()=>validateProject(p)).toThrow('ordered');p.layout.cutPositions=[.3,.7];p.composition.crop.x=.4;expect(()=>validateProject(p)).toThrow('Crop');expect(partitionAxes(neutral(),1500,1000)).toEqual({xs:[0,1500],ys:[0,1000]});});
});
describe('Input safety',()=>{
 it('sniffs supported signatures and rejects corrupt or unsupported input',()=>{expect(inspectHeader(new Uint8Array(fs.readFileSync('tests/fixtures/colour-chart.png')))).toMatchObject({width:600,height:400,type:'image/png'});expect(inspectHeader(new Uint8Array(fs.readFileSync('tests/fixtures/orientation-6.jpg')))).toMatchObject({width:120,height:80,type:'image/jpeg'});expect(()=>inspectHeader(new Uint8Array(fs.readFileSync('tests/fixtures/corrupt.png')))).toThrow();expect(()=>inspectHeader(new TextEncoder().encode('<svg/>'))).toThrow('JPEG');});
 it('rejects animation headers and oversized decoded dimensions',()=>{const b=new Uint8Array(fs.readFileSync('tests/fixtures/colour-chart.png')),d=new DataView(b.buffer);d.setUint32(16,12001);expect(()=>inspectHeader(b)).toThrow('large');const animated=new Uint8Array(53);animated.set([137,80,78,71,13,10,26,10]);const v=new DataView(animated.buffer);v.setUint32(8,13);animated.set(new TextEncoder().encode('IHDR'),12);v.setUint32(16,10);v.setUint32(20,10);v.setUint32(33,8);animated.set(new TextEncoder().encode('acTL'),37);expect(()=>inspectHeader(animated)).toThrow('Animated');});
});

describe('Independent piece photos',()=>{
 it('migrates existing schema 3 projects without changing their layout',()=>{const p:any=initialProject();p.schemaVersion=3;delete p.pieces;delete p.layout.photoMode;const q=importRecipe(JSON.stringify(p));expect(q.project.layout.photoMode).toBe('continuous');expect(q.project.pieces).toEqual({});expect(q.project.schemaVersion).toBe(5);});
 it('validates piece crops and keeps moved, rotated corners inside the output frame',()=>{const p=neutral();p.layout.mode='strips';p.pieces={'strips:horizontal:0:0':{source:null,crop:{x:0,y:0,width:1,height:1},fit:'cover',rotationDeg:45,offsetX:-20,offsetY:-20,exposureEv:0,contrast:0,warmth:0}};validateProject(p);const g=buildGeometry(p,600,400);for(const piece of g.pieces){const c=Math.cos(piece.angle),s=Math.sin(piece.angle);for(const x of [-piece.width/2,piece.width/2])for(const y of [-piece.height/2,piece.height/2]){const px=g.originX+piece.x+piece.dx+piece.width/2+x*c-y*s,py=g.originY+piece.y+piece.dy+piece.height/2+x*s+y*c;expect(px).toBeGreaterThanOrEqual(g.margin-.001);expect(py).toBeGreaterThanOrEqual(g.margin-.001);expect(px).toBeLessThanOrEqual(g.stageWidth-g.margin+.001);expect(py).toBeLessThanOrEqual(g.stageHeight-g.margin+.001);}}p.pieces['strips:horizontal:0:0'].crop.x=.5;expect(()=>validateProject(p)).toThrow('Crop');});
});

// Edge regressions: old recipes gain neutral controls; adjacent torn pieces must match.
describe('Fibrous edge recipes',()=>{
 it('migrates schema 4, validates new controls and preserves detail settings',()=>{
  const p:any=initialProject();p.schemaVersion=4;p.rendererVersion='0.4.0';
  for(const key of ['outerFray','innerFray','exposedPaper','fibreLength','longFibres','fibreClumping'])delete p.edges[key];
  const q=importRecipe(JSON.stringify(p));expect(q.project.schemaVersion).toBe(5);expect(q.project.edges.exposedPaper).toBe(0);expect(q.project.edges.longFibres).toBe(0);expect(q.project.tone).toEqual(p.tone);expect(q.project.layout).toEqual(p.layout);expect(q.notes.join(' ')).toContain('Migrated schema 4 to 5');
  q.project.edges.fibreLength=101;expect(()=>validateProject(q.project)).toThrow('fibreLength');
 });
 it('identifies shared cuts exactly and keeps framing fixed as fibres change',()=>{
  const p=initialProject();p.layout.mode='grid';p.layout.rows=2;p.layout.columns=2;p.layout.tearAmount=100;p.edges.strength=100;p.edges.irregularity=100;
  const g=buildGeometry(p,600,400),[a,b,c]=g.pieces;
  expect(a.boundaries[1].kind).toBe('inner');expect(a.boundaries[1].points).toEqual([...b.boundaries[3].points].reverse());expect(a.boundaries[2].points).toEqual([...c.boundaries[0].points].reverse());expect(a.boundaries[0].kind).toBe('outer');
  p.edges.fibreLength=100;p.edges.longFibres=100;p.edges.outerFray=0;p.edges.innerFray=0;
  expect(buildGeometry(p,600,400)).toEqual(g);
 });
});
