import {z} from 'zod';
import {inspectHeader} from '../imaging/input';
export const channels=['albedo','height','normal','roughness','coating','fibre'] as const;
export type Channel=(typeof channels)[number];
const mapSchema=z.object({file:z.string().regex(/^[a-zA-Z0-9_. -]+$/),sha256:z.string().regex(/^[a-f0-9]{64}$/),colourSpace:z.enum(['srgb','linear']),status:z.enum(['captured','inferred','procedural'])}).strict();
export const manifestSchema=z.object({id:z.string().regex(/^[a-z0-9-]+$/),version:z.string().max(30),author:z.string().min(1).max(200),source:z.string().max(500),permission:z.string().min(1).max(1000),status:z.enum(['captured','procedural','hybrid']),sampleWidthMm:z.number().gt(0).max(2000),sampleHeightMm:z.number().gt(0).max(2000),width:z.number().int().min(1).max(4096),height:z.number().int().min(1).max(4096),tiling:z.literal('repeat'),fibreDirectionDeg:z.number().min(0).max(360),normalConvention:z.literal('OpenGL +Y'),maps:z.object(Object.fromEntries(channels.map(c=>[c,mapSchema.optional()]))).strict()}).strict();
export type MaterialManifest=z.infer<typeof manifestSchema>;
export interface MaterialAsset {manifest:MaterialManifest;maps:Partial<Record<Channel,ImageBitmap>>;files:File[];}
export async function loadMaterialFiles(files:File[]):Promise<MaterialAsset>{
 const json=files.find(f=>f.name.endsWith('.json'));if(!json||json.size>262144)throw new Error('Choose a material manifest JSON (up to 256 KB) and its map images together.');
 const parsed=manifestSchema.safeParse(JSON.parse(await json.text()));if(!parsed.success)throw new Error(`Invalid material manifest: ${parsed.error.issues[0].message}`);const manifest=parsed.data;const maps:MaterialAsset['maps']={};
 try{for(const channel of channels){const info=manifest.maps[channel];if(!info)continue;if(channel!=='albedo'&&info.colourSpace!=='linear')throw new Error(`${channel} is a data map and must be linear.`);const file=files.find(f=>f.name===info.file);if(!file)throw new Error(`Missing material map: ${info.file}`);if(file.size>24*1024*1024)throw new Error('Material map exceeds 24 MB.');const bytes=await file.arrayBuffer();const header=inspectHeader(new Uint8Array(bytes));if(header.width!==manifest.width||header.height!==manifest.height)throw new Error("Material map header dimensions do not match its manifest.");const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');if(hash!==info.sha256)throw new Error(`Hash mismatch in ${info.file}.`);const bitmap=await createImageBitmap(file,{imageOrientation:'none',colorSpaceConversion:channel==='albedo'?'default':'none',premultiplyAlpha:'none'});if(bitmap.width!==manifest.width||bitmap.height!==manifest.height){bitmap.close();throw new Error('All material maps must match declared dimensions and alignment.');}maps[channel]=bitmap;}if(!Object.keys(maps).length)throw new Error('The material set contains no maps.');return {manifest,maps,files};}catch(e){Object.values(maps).forEach(b=>b?.close());throw e;}
}

