import {Range,Select,Colour} from './Controls';
import type {EditProps} from './Controls';
import {backgroundStyles} from '../model/backgrounds';
import {controls} from '../model/project';
export function AlbumControls(props:EditProps&{choose:(id:string)=>void;newPattern:()=>void}){
 const {project:p,change,begin,end}=props,s=p.stage,textured=s.background==='solid'&&s.material!=='plain';
 const fields=['texture','aging','stains','edgeShade','binding'];
 function parameter(key:string){const c=controls.find(c=>c.key==='stage.'+key)!;return <Range key={key} label={c.label} value={s[key as keyof typeof s] as number} min={c.min} max={c.max} step={c.step} onChange={v=>change('stage.'+key,v)} begin={begin} end={end} disabled={!textured} note={c.description}/>;}
 return <details className="advanced album-controls" open><summary>Album background <span>+</span></summary><div className="album-body"><Select label="Background" value={s.background} options={[{value:'solid',label:'Include background'},{value:'transparent',label:'Transparent'}]} onChange={v=>change('stage.background',v)}/><Select label="Background material" value={s.material} options={backgroundStyles.map(b=>({value:b.id,label:b.name}))} onChange={props.choose}/><Colour label="Background colour" value={s.colour} onChange={v=>change('stage.colour',v)}/><Range label="Surrounding space" value={s.paddingPct} max={30} unit="%" onChange={v=>change('stage.paddingPct',v)} begin={begin} end={end}/>{s.material!=='plain'&&<>{fields.slice(0,2).map(parameter)}<details className="advanced"><summary>Background details <span>+</span></summary>{fields.slice(2).map(parameter)}{parameter('textureScale')}<button className="text-link" onClick={props.newPattern} disabled={!textured}>New background pattern</button></details></>}<Select label="Photo corner mounts" value={s.mounts} options={[{value:'none',label:'None'},{value:'black',label:'Black paper pockets'},{value:'ivory',label:'Ivory paper pockets'},{value:'kraft',label:'Kraft paper pockets'}]} onChange={v=>change('stage.mounts',v)} disabled={s.background==='transparent'}/>{s.mounts!=='none'&&<Range label="Mount corner size" value={s.mountSize} min={2} max={15} step={.5} unit="%" onChange={v=>change('stage.mountSize',v)} begin={begin} end={end} disabled={s.background==='transparent'}/>}<small className="group-help">Album paper sits behind the print. Mounts follow each piece and its rotation. Transparent exports omit the album and its mounts.</small></div></details>;
}
