import {useId,useState} from 'react';
import {ChevronDown,RotateCcw,Shuffle,Info} from 'lucide-react';
import {controls,getValue,groups} from '../model/project';
import type {Project,Group,Control} from '../model/project';
import {edgeStyles} from '../model/edge-styles';
import {filmById,films,materials} from '../model/profiles';
export interface EditProps {project:Project;change:(key:string,value:unknown)=>void;begin:()=>void;end:()=>void;}
export function Range({label,value,min=0,max=100,step=1,onChange,begin,end,disabled=false,note,unit='',testId}:{label:string;value:number;min?:number;max?:number;step?:number;onChange:(n:number)=>void;begin?:()=>void;end?:()=>void;disabled?:boolean;note?:string;unit?:string;testId?:string}){const id=useId();return <div className={`parameter ${disabled?'muted':''}`} title={note}><div className="parameter-heading"><label htmlFor={id}>{label}</label><div className="numeric"><input aria-label={`${label} value`} type="number" value={Number(value.toFixed(2))} min={min} max={max} step={step} disabled={disabled} onFocus={begin} onBlur={end} onChange={e=>{if(e.target.value!=='')onChange(Math.max(min,Math.min(max,Number(e.target.value))));}}/>{unit&&<span>{unit}</span>}</div></div><input id={id} data-testid={testId} aria-label={label} type="range" min={min} max={max} step={step} value={value} disabled={disabled} onPointerDown={begin} onPointerUp={end} onPointerCancel={end} onKeyDown={e=>{if(e.key.startsWith('Arrow')||e.key==='Home'||e.key==='End')begin?.();}} onKeyUp={end} onChange={e=>onChange(Number(e.target.value))}/>{disabled&&note&&<small className="dependency">{note}</small>}</div>;}
export function Select({label,value,options,onChange,disabled=false}:{label:string;value:string;options:(string|{value:string;label:string})[];onChange:(v:string)=>void;disabled?:boolean}){const id=useId();return <div className="select-field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={e=>onChange(e.target.value)} disabled={disabled}>{options.map(o=>typeof o==='string'?<option key={o} value={o}>{o.charAt(0).toUpperCase()+o.slice(1)}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></div>;}
export function Colour({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){const id=useId();return <label className="colour-field" htmlFor={id}><span>{label}</span><span className="colour-value">{value}<input id={id} aria-label={label} type="color" value={value} onChange={e=>onChange(e.target.value.toUpperCase())}/></span></label>;}
const groupNames:Record<Group,string>={tone:'Basic tone',film:'Film response',bw:'Black & white',grain:'Photographic grain',paper:'Paper material',ink:'Ink & print',edges:'Paper edges',wrinkles:'Wrinkles',lighting:'Light & depth'};
const primary:Record<Group,string[]>={tone:['exposureEv','contrast','detailSoftness'],film:[],bw:['printContrast'],grain:['size'],paper:['tooth','fibres'],ink:['spread','densityVariation'],edges:['cornerRadius','rimWear','outerFray','innerFray','irregularity','featherWidth','exposedPaper','looseFibres','fibreLength','longFibres'],wrinkles:['scale','density','definition'],lighting:['azimuthDeg','relief','shadowOpacity']};
export function Inspector(props:EditProps&{reset:(g:Group)=>void;randomize:(g:Group)=>void;loadFilm:(id:string)=>void;loadMaterial:(id:string)=>void;achromatic:boolean;loadMaps:()=>void;assetName?:string;edgeStyle:(id:string)=>void;crumple:()=>void;preserveDetail:()=>void;}){
 const {project:p,change}=props;const [open,setOpen]=useState<Set<Group>>(new Set(['film','bw','paper']));const [info,setInfo]=useState<string|null>(null);const film=filmById(p.film.profile),material=materials.find(m=>m.id===p.paper.profile);
 function parameter(c:Control){let disabled=false,note=c.description;if(c.key==='edges.innerFray'&&(p.layout.mode==='single'||p.layout.tearAmount===0)){disabled=true;note='Use Strips or Grid and raise Torn inner edges to fray the joins.';}if(c.key==='edges.outerFray'&&p.edges.profile==='clean'){disabled=true;note='Choose Deckled or Torn for the outer cut.';}if(c.key==='film.colourMix'&&film?.family==='bw'){disabled=true;note='Colour character is inactive for a monochrome film.';}if((c.key.startsWith('bw.mixer')||c.key==='bw.filterAmount')&&props.achromatic){disabled=true;note='This source is already monochrome; colour sensitivity has no effect.';}if(c.key==='grain.chroma'&&p.bw.enabled&&p.bw.strength*p.finishStrength===10000){disabled=true;note='Full B&W suppresses coloured grain. This value is retained.';}if(c.key==='paper.assetMix'&&!props.assetName){disabled=true;note='Install a material map set to blend captured or inferred fields.';}if(c.key==='paper.roughness'&&(!p.lighting.enabled||p.lighting.strength===0||p.paper.sheen===0)){disabled=true;note='Enable lighting and surface sheen to change reflection width.';}return <Range key={c.key} label={c.label} value={getValue(p,c.key) as number} min={c.min} max={c.max} step={c.step} disabled={disabled||!p[c.group as Group]?.enabled} note={note} onChange={v=>change(c.key,v)} begin={props.begin} end={props.end} unit={c.key==='edges.cornerRadius'?'%':c.key.endsWith('Deg')?'°':c.key.endsWith('Ev')?'EV':''}/>;}
 return <aside className="inspector" aria-label="Effect controls"><div className="inspector-title"><span className="eyebrow">THE FINISH</span><span className="tiny">Independent layers</span></div><div className="finish-master"><Range label="Finish strength" value={p.finishStrength} onChange={v=>change('finishStrength',v)} begin={props.begin} end={props.end} unit="%"/><small>A little character. Or a little more.</small></div>
 {groups.map(g=>{const opened=open.has(g),fields=controls.filter(c=>c.group===g),strength=fields.find(c=>c.key===`${g}.strength`)!;return <section className={`effect-group ${!p[g].enabled?'bypassed':''}`} key={g}><div className="group-heading"><button className="group-title" aria-expanded={opened} onClick={()=>setOpen(prev=>{const next=new Set(prev);next.has(g)?next.delete(g):next.add(g);return next;})}><ChevronDown size={14} className={opened?'':'closed'}/>{groupNames[g]}</button><label className="toggle" title={`Bypass ${groupNames[g]}`}><input aria-label={`Enable ${groupNames[g]}`} type="checkbox" checked={p[g].enabled} onChange={e=>change(`${g}.enabled`,e.target.checked)}/><span/></label></div>{opened&&<div className="group-body">
 {g==='film'&&<><Select label="Film profile" value={p.film.profile} options={[{value:'none',label:'None · neutral response'},...films.map(f=>({value:f.id,label:f.name}))]} onChange={props.loadFilm}/><button className="text-link info-link" onClick={()=>setInfo(info==='film'?null:'film')}><Info size={12}/> Film-inspired · profile notes</button>{info==='film'&&<div className="info-card">{film?<><strong>{film.name}</strong><p>{film.description}</p><p>{film.calibrationStatus}. Development changes the tone curve and active grain, without changing exposure.</p><a href={film.referenceSources[0]} target="_blank" rel="noreferrer">Reference data ↗</a><code>v{film.version} · {film.hash}</code></>:<p>No stock curve. Manual balance, halo and glow remain available.</p>}</div>}</>}
 {g==='paper'&&<><Select label="Paper type" value={p.paper.profile} options={materials.map(m=>({value:m.id,label:m.name}))} onChange={props.loadMaterial}/><button className="text-link info-link" onClick={()=>setInfo(info==='paper'?null:'paper')}><Info size={12}/> {props.assetName||'Original procedural material'}</button>{info==='paper'&&<div className="info-card"><strong>{material?.name}</strong><p>{material?.description}</p><p>{props.assetName?`Installed map set: ${props.assetName}`:'Original procedural approximation, not a measured scan. The three captured-material library sets remain an unfinished asset gate.'}</p><button onClick={props.loadMaps}>Install material maps…</button><small>Select the manifest and its map images together.</small></div>}</>}
 {parameter(strength)}
 {g==='bw'&&<Select label="Lens filter look" value={p.bw.filter} options={['none','yellow','orange','red','green','blue']} disabled={props.achromatic} onChange={v=>change('bw.filter',v)}/>}
 {g==='wrinkles'&&<><Select label="Wrinkle style" value={p.wrinkles.style} options={[{value:'creased',label:'Soft creases'},{value:'crumpled',label:'Crumpled paper'}]} onChange={v=>change('wrinkles.style',v)}/><button className="crumple-recipe" onClick={props.crumple}>Use reference crumple</button><small className="group-help">Loads crumpled kozo and raking light. Keeps your photo, tone, film, crop and layout.</small>{(!p.lighting.enabled||p.lighting.strength===0||p.lighting.relief===0)&&<small className="dependency">Use Object view and enable Light &amp; depth with Surface relief to see the folds.</small>}</>}
 {g==='tone'&&<><button className="text-link" onClick={props.preserveDetail} disabled={p.tone.detailSoftness===0&&p.ink.spread===0}>Remove softening</button><small className="group-help">Image softness controls detail loss. Set it and Ink softness to 0 to remove deliberate softening. This never sharpens beyond the original. Inspect at 100% after the preview refines.</small></>}
 {g==='edges'&&<><div className="edge-recipes" aria-label="Edge starting points">{edgeStyles.map(s=><button key={s.id} title={s.note} onClick={()=>props.edgeStyle(s.id)}>{s.name}</button>)}</div><Select label="Outer cut" value={p.edges.profile} options={['deckled','torn','clean']} onChange={v=>change('edges.profile',v)}/><Select label="Round corners on" value={p.edges.cornerScope} options={[{value:'sheet',label:'Outside sheet corners'},{value:'pieces',label:'Every piece'}]} onChange={v=>change('edges.cornerScope',v)}/><small className="group-help">Rounded washi adds uneven soft corners and a worn rim. Choose a starting point, then adjust outside and inside fraying separately. Exposed paper reveals the support colour; Long strands adds loose threads. Zoom in to see individual fibres.</small>{p.layout.mode!=='single'&&p.layout.tearAmount===0&&<small className="dependency">Raise Torn inner edges in Layout to fray the joins.</small>}{p.edges.profile==='clean'&&<small className="dependency">Clean outer cuts have no outside fraying. Inner tears remain independent.</small>}</>}
 {primary[g].flatMap(key=>fields.filter(c=>c.key===`${g}.${key}`)).map(parameter)}
 {g==='paper'&&<Colour label="Paper colour" value={p.paper.colour} onChange={v=>change('paper.colour',v)}/>}
 <details className="advanced"><summary>Fine adjustments <span>+</span></summary><div>{g==='grain'&&<Select label="Film format feel" value={p.grain.format} options={[{value:'35mm',label:'35 mm'},{value:'medium',label:'Medium format'},{value:'large',label:'Large format'}]} onChange={v=>change('grain.format',v)}/>}{g==='bw'&&<Select label="Print tone" value={p.bw.toner} options={['neutral','sepia','cool','selenium']} onChange={v=>change('bw.toner',v)}/>} {fields.filter(c=>c!==strength&&!primary[g].includes(c.key.split('.')[1])).map(parameter)}</div></details>
 {g==='film'&&<small className="group-help">Film changes load film, grain and B&W as one undo step. Each remains adjustable.</small>}
 {g==='lighting'&&p.paper.tooth===0&&p.wrinkles.strength===0&&<small className="dependency">Surface relief needs paper texture or wrinkles.</small>}
 <div className="group-actions"><button onClick={()=>props.reset(g)}><RotateCcw size={12}/>Reset group</button>{['grain','paper','ink','edges','wrinkles'].includes(g)&&<button onClick={()=>props.randomize(g)}><Shuffle size={12}/>New pattern</button>}</div></div>}</section>;})}</aside>;
}
