import {useEffect,useRef,useState} from 'react';
import type {Project} from '../model/project';
import {Modal} from './Modal';
import {Range,Select} from './Controls';
type Crop=Project['composition']['crop'];
export function CropTool({bitmap,crop,onApply,onClose}:{bitmap:ImageBitmap;crop:Crop;onApply:(c:Crop)=>void;onClose:()=>void}){const [value,setValue]=useState(crop);const [aspect,setAspect]=useState('free');const canvas=useRef<HTMLCanvasElement>(null),area=useRef<HTMLDivElement>(null);const gesture=useRef<{x:number;y:number;crop:Crop;mode:string}|null>(null);
 useEffect(()=>{const c=canvas.current!;c.width=bitmap.width;c.height=bitmap.height;c.getContext('2d')!.drawImage(bitmap,0,0);},[bitmap]);
 function enforce(c:Crop){c.width=Math.max(.03,Math.min(1,c.width));c.height=Math.max(.03,Math.min(1,c.height));c.x=Math.max(0,Math.min(1-c.width,c.x));c.y=Math.max(0,Math.min(1-c.height,c.y));setValue(c);}
 function ratio(v:string){setAspect(v);if(v==='free')return;const [w,h]=v.split(':').map(Number),r=w/h/(bitmap.width/bitmap.height);let width=value.width,height=width/r;if(height>1){height=1;width=r;}enforce({x:value.x+(value.width-width)/2,y:value.y+(value.height-height)/2,width,height});}
 return <Modal title="Crop your photograph" onClose={onClose} wide><p className="modal-intro">Drag the frame to move it. Drag a corner to resize. The source file stays untouched.</p><div className="crop-area" ref={area} style={{aspectRatio:bitmap.width/bitmap.height,width:`min(100%, ${400*bitmap.width/bitmap.height}px)`}} onPointerMove={e=>{const g=gesture.current;if(!g)return;const rect=area.current!.getBoundingClientRect(),dx=(e.clientX-g.x)/rect.width,dy=(e.clientY-g.y)/rect.height;let c={...g.crop};if(g.mode==='move'){c.x+=dx;c.y+=dy;}else if(g.mode==='br'){c.width+=dx;c.height+=dy;}else{c.x+=dx;c.y+=dy;c.width-=dx;c.height-=dy;}if(aspect!=='free'&&g.mode!=='move'){const [w,h]=aspect.split(':').map(Number);c.height=c.width/(w/h)*bitmap.width/bitmap.height;}enforce(c);}} onPointerUp={()=>gesture.current=null} onPointerCancel={()=>gesture.current=null}><canvas ref={canvas}/><div className="crop-frame" style={{left:`${value.x*100}%`,top:`${value.y*100}%`,width:`${value.width*100}%`,height:`${value.height*100}%`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);gesture.current={x:e.clientX,y:e.clientY,crop:value,mode:(e.target as HTMLElement).dataset.corner||'move'};}}><div className="thirds"/><button data-corner="tl" aria-label="Resize top left crop" className="crop-handle tl"/><button data-corner="br" aria-label="Resize bottom right crop" className="crop-handle br"/></div></div><div className="crop-controls"><Select label="Crop proportions" value={aspect} options={['free','1:1','3:2','2:3','4:5']} onChange={ratio}/><Range label="Crop zoom" value={Math.round(100/Math.max(value.width,value.height))} min={100} max={500} onChange={n=>{const factor=Math.max(value.width,value.height)*n/100;const width=value.width/factor,height=value.height/factor;enforce({x:value.x+(value.width-width)/2,y:value.y+(value.height-height)/2,width,height});}}/>{(['x','y','width','height'] as const).map(key=><label key={key} className="small-number">{key} %<input aria-label={`Crop ${key} percent`} type="number" min={0} max={100} step={.1} value={+(value[key]*100).toFixed(2)} onChange={e=>enforce({...value,[key]:Number(e.target.value)/100})}/></label>)}</div><div className="modal-actions"><button onClick={()=>setValue({x:0,y:0,width:1,height:1})}>Reset crop</button><button className="primary" onClick={()=>{onApply(value);onClose();}}>Apply crop</button></div></Modal>;
}

