import {useEffect,useMemo,useRef,useState} from 'react';
import {Modal} from './Modal';
import {Range,Select} from './Controls';
import type {Project} from '../model/project';
import {emptyPiece,updatePiece} from '../model/pieces';
import type {PieceEdit} from '../model/pieces';
import {buildGeometry,pieceImagePlacement} from '../layout/geometry';

type Framing=Pick<PieceEdit,'crop'|'fit'>;
export function PieceFraming({project,slotKey,pieceId,label,bitmap,mainWidth,mainHeight,getPreview,onPreview,onApply,onCancel}:{project:Project;slotKey:string;pieceId:string;label:string;bitmap:ImageBitmap;mainWidth:number;mainHeight:number;getPreview:()=>ImageBitmap|null;onPreview:(v:Framing)=>void;onApply:()=>void;onCancel:()=>void}){
 const initial=project.pieces[slotKey]??emptyPiece();
 const geometry=useMemo(()=>buildGeometry(project,mainWidth,mainHeight),[project,mainWidth,mainHeight]);
 const piece=geometry.pieces.find(p=>p.id===pieceId)!;
 const [value,setValue]=useState<Framing>(()=>{const place=pieceImagePlacement(project,piece,bitmap.width,bitmap.height);return {crop:place.crop,fit:initial.fit};});
 const current=useRef(value);current.current=value;const canvas=useRef<HTMLCanvasElement>(null),frame=useRef<HTMLCanvasElement>(null),gesture=useRef<{x:number;y:number;crop:PieceEdit['crop']}|null>(null);
 const outline=useRef({geometry,piece});outline.current={geometry,piece};
 const local=updatePiece(project,slotKey,value),place=pieceImagePlacement(local,piece,bitmap.width,bitmap.height),pad=16;
 const base=pieceImagePlacement(updatePiece(project,slotKey,{crop:emptyPiece().crop,fit:value.fit}),piece,bitmap.width,bitmap.height).crop;
 const zoom=Math.max(100,100*Math.max(base.width/value.crop.width,base.height/value.crop.height));
 function change(next:Framing){const crop=next.fit==='cover'?pieceImagePlacement(updatePiece(project,slotKey,next),piece,bitmap.width,bitmap.height).crop:{...next.crop};crop.width=Math.max(.01,Math.min(1,crop.width));crop.height=Math.max(.01,Math.min(1,crop.height));crop.x=Math.max(0,Math.min(1-crop.width,crop.x));crop.y=Math.max(0,Math.min(1-crop.height,crop.y));const v={...next,crop};current.current=v;setValue(v);onPreview(v);}
 function zoomTo(n:number,u=.5,v=.5){const old=current.current.crop,factor=Math.max(1,Math.min(5,n/100)),width=base.width/factor,height=base.height/factor;change({...current.current,crop:{x:old.x+old.width*u-width*u,y:old.y+old.height*v-height*v,width,height}});}
 useEffect(()=>{const c=canvas.current!;const scale=Math.min(1100/(piece.width+pad*2),650/(piece.height+pad*2));c.width=Math.ceil((piece.width+pad*2)*scale);c.height=Math.ceil((piece.height+pad*2)*scale);const ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);ctx.setTransform(scale,0,0,scale,(pad-piece.x)*scale,(pad-piece.y)*scale);const path=new Path2D();piece.points.forEach(([x,y],i)=>i?path.lineTo(x,y):path.moveTo(x,y));path.closePath();ctx.save();ctx.clip(path);ctx.fillStyle=project.paper.colour;ctx.fillRect(piece.x-pad,piece.y-pad,piece.width+2*pad,piece.height+2*pad);const crop=place.crop;ctx.drawImage(bitmap,crop.x*bitmap.width,crop.y*bitmap.height,crop.width*bitmap.width,crop.height*bitmap.height,place.x,place.y,place.width,place.height);ctx.restore();ctx.strokeStyle='#667759';ctx.lineWidth=1/scale;ctx.stroke(path);},[bitmap,project.paper.colour,piece,place.crop.x,place.crop.y,place.crop.width,place.crop.height,place.x,place.y,place.width,place.height]);
 useEffect(()=>{let id=0,last:ImageBitmap|null=null;const paint=()=>{const b=getPreview(),c=frame.current;if(b&&b!==last&&c&&b.width){c.width=b.width;c.height=b.height;const ctx=c.getContext('2d')!;ctx.drawImage(b,0,0);const {geometry:g,piece:q}=outline.current,scale=Math.min(c.width/g.stageWidth,c.height/g.stageHeight);ctx.save();ctx.translate((c.width-g.stageWidth*scale)/2+(g.originX+q.x+q.dx+q.width/2)*scale,(c.height-g.stageHeight*scale)/2+(g.originY+q.y+q.dy+q.height/2)*scale);ctx.rotate(q.angle);ctx.scale(scale,scale);ctx.translate(-q.x-q.width/2,-q.y-q.height/2);ctx.beginPath();q.points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.strokeStyle='#ccb86e';ctx.lineWidth=2/scale;ctx.stroke();ctx.restore();last=b;}id=requestAnimationFrame(paint);};paint();return()=>cancelAnimationFrame(id);},[getPreview]);
 const zoomAction=useRef(zoomTo);zoomAction.current=zoomTo;
 useEffect(()=>{const c=canvas.current!;const wheel=(e:WheelEvent)=>{e.preventDefault();const rect=c.getBoundingClientRect(),v=current.current,baseProject=updatePiece(project,slotKey,{crop:emptyPiece().crop,fit:v.fit}),b=pieceImagePlacement(baseProject,piece,bitmap.width,bitmap.height).crop;const currentZoom=100*Math.max(b.width/v.crop.width,b.height/v.crop.height);zoomAction.current(currentZoom*Math.exp(-e.deltaY*.0015),(e.clientX-rect.left)/rect.width,(e.clientY-rect.top)/rect.height);};c.addEventListener('wheel',wheel,{passive:false});return()=>c.removeEventListener('wheel',wheel);},[project,slotKey,piece,bitmap]);
 function move(dx:number,dy:number,crop:PieceEdit['crop']){const rect=canvas.current!.getBoundingClientRect();change({...current.current,crop:{...crop,x:crop.x-dx/rect.width*(piece.width+pad*2)/place.width*place.crop.width,y:crop.y-dy/rect.height*(piece.height+pad*2)/place.height*place.crop.height}});}
 return <Modal title={'Frame '+label.toLowerCase()} wide onClose={onCancel}>
  <p className="modal-intro">Drag the photo inside its paper section. Scroll or use zoom to get closer. The whole artwork updates as you move.</p>
  <div className="section-framing-layout"><div className="section-framing-focus"><div className="framing-label">THIS SECTION <span>Photo placement</span></div><div className="section-framing-surface"><canvas ref={canvas} tabIndex={0} aria-label="Section crop preview; drag to position, scroll to zoom, arrow keys to move" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);gesture.current={x:e.clientX,y:e.clientY,crop:{...current.current.crop}};}} onPointerMove={e=>{if(gesture.current){const g=gesture.current;move(e.clientX-g.x,e.clientY-g.y,g.crop);}}} onPointerUp={()=>gesture.current=null} onPointerCancel={()=>gesture.current=null} onKeyDown={e=>{const keys:Record<string,[number,number]>={ArrowLeft:[-10,0],ArrowRight:[10,0],ArrowUp:[0,-10],ArrowDown:[0,10]};if(keys[e.key]){e.preventDefault();move(...keys[e.key],current.current.crop);}if(e.key==='+'||e.key==='='){e.preventDefault();zoomTo(zoom*1.1);}if(e.key==='-'){e.preventDefault();zoomTo(zoom/1.1);}}}/><div className="framing-grid" aria-hidden="true"/></div><small>The outline matches this section. Paper finish, tone, tilt and lighting appear in the whole-frame preview.</small></div><div className="section-framing-context"><div className="framing-label">WHOLE FRAME <span>Live finished preview</span></div><canvas ref={frame} aria-label="Live whole-frame crop preview"/></div></div>
  <div className="section-framing-controls"><Select label="Crop fit" value={value.fit} options={[{value:'cover',label:'Fill section'},{value:'contain',label:'Show whole crop'}]} onChange={fit=>change({fit:fit as PieceEdit['fit'],crop:emptyPiece().crop})}/><Range label="Crop zoom" min={100} max={500} value={zoom} unit="%" onChange={n=>zoomTo(n)}/><Range label="Photo horizontal position" min={0} max={100} step={.1} value={value.crop.width>=.999999?50:value.crop.x/(1-value.crop.width)*100} disabled={value.crop.width>=.999999} onChange={n=>change({...value,crop:{...value.crop,x:(1-value.crop.width)*n/100}})}/><Range label="Photo vertical position" min={0} max={100} step={.1} value={value.crop.height>=.999999?50:value.crop.y/(1-value.crop.height)*100} disabled={value.crop.height>=.999999} onChange={n=>change({...value,crop:{...value.crop,y:(1-value.crop.height)*n/100}})}/></div>
  <div className="modal-actions"><button onClick={()=>change({fit:value.fit,crop:base})}>Reset framing</button><button onClick={onCancel}>Cancel</button><button className="primary" onClick={onApply}>Apply crop</button></div>
 </Modal>;
}
