import {useEffect,useRef,useState} from 'react';
import {Upload,Crop,RotateCcw,ArrowLeft,ArrowRight} from 'lucide-react';
import {Range,Select} from './Controls';
import {PieceFraming} from './PieceFraming';
import type {Project} from '../model/project';
import type {DecodedSource} from '../imaging/input';
import {emptyPiece,pieceSlots,updatePiece} from '../model/pieces';
import type {PieceEdit} from '../model/pieces';

function PhotoThumb({photo}:{photo:DecodedSource|null}){const [url,setUrl]=useState('');useEffect(()=>{if(!photo){setUrl('');return;}const u=URL.createObjectURL(photo.blob);setUrl(u);return()=>URL.revokeObjectURL(u);},[photo]);return url?<img src={url} alt=""/>:<span className="piece-missing">Choose photo</span>;}
export function PieceEditor({project:p,edit,begin,end,main,photos,onPhotos,busy,getPreview,onFrameStart}:{project:Project;edit:(p:Project)=>void;begin:()=>void;end:()=>void;main:DecodedSource|null;photos:Map<string,DecodedSource>;onPhotos:(files:File[],key:string|null)=>void;busy:boolean;getPreview:()=>ImageBitmap|null;onFrameStart:()=>void}){
 const slots=pieceSlots(p),[selected,setSelected]=useState(''),[cropping,setCropping]=useState<PieceEdit|null>(null),input=useRef<HTMLInputElement>(null),uploadKey=useRef<string|null>(null);
 const slot=slots.find(s=>s.key===selected)??slots[0];if(!slot)return null;
 const value=p.pieces[slot.key]??emptyPiece(),photo=value.source?photos.get(value.source.id)??null:main,individual=p.layout.photoMode==='individual';
 const patch=(next:Partial<PieceEdit>)=>edit(updatePiece(p,slot.key,next));
 function choose(key:string|null){uploadKey.current=key;input.current?.click();}
 function move(direction:number){const index=slots.indexOf(slot),other=slots[index+direction];if(!other)return;edit({...p,pieces:{...p.pieces,[slot.key]:p.pieces[other.key]??emptyPiece(),[other.key]:value}});setSelected(other.key);}
 return <section className="piece-editor" aria-label="Individual pieces">
  <input ref={input} hidden type="file" multiple accept="image/jpeg,image/png,image/webp" aria-label="Choose photos for pieces" onChange={e=>{const files=Array.from(e.target.files??[]);if(files.length)onPhotos(files,uploadKey.current);e.target.value='';}}/>
  <Select label="Photos in pieces" value={p.layout.photoMode} options={[{value:'continuous',label:'One photo across all pieces'},{value:'individual',label:'Different photo per piece'}]} onChange={v=>edit({...p,layout:{...p.layout,photoMode:v}})}/>
  {individual&&<><button className="piece-upload" disabled={busy} onClick={()=>choose(null)}><Upload size={14}/>{busy?'Reading photos...':'Choose photos in order'}</button><small className="group-help">Choose a piece below, or drop a photo onto it. Film and paper are shared across the frame.</small><button className="text-link" onClick={()=>edit({...p,composition:{...p.composition,aspect:'2:3',borderPct:0},layout:{...p.layout,mode:'strips',direction:'horizontal',stripCount:3,cutPositions:[1/3,2/3],gapPct:2,tearAmount:75,photoMode:'individual'}})}>Make a portrait triptych</button></>}
  <div className="piece-choices">{slots.map((s,i)=>{const e=p.pieces[s.key]??emptyPiece(),image=e.source?photos.get(e.source.id)??null:main;return <button key={s.key} className={s.key===slot.key?'selected':''} aria-label={'Select '+s.label} aria-pressed={s.key===slot.key} onClick={()=>{setSelected(s.key);setCropping(null);}} onDragOver={e=>{e.preventDefault();e.stopPropagation();}} onDrop={e=>{e.preventDefault();e.stopPropagation();setSelected(s.key);if(e.dataTransfer.files.length)onPhotos(Array.from(e.dataTransfer.files),s.key);}}><PhotoThumb photo={image}/><span>{i+1}</span></button>;})}</div>
  <div className="piece-heading"><strong>{slot.label}</strong>{individual&&<span title={value.source?.name??main?.info.name}>{value.source?.name??'Main photo'}</span>}</div>
  {individual&&<><div className="piece-actions"><button disabled={busy} onClick={()=>choose(slot.key)}><Upload size={13}/>Choose photo</button><button disabled={!photo||busy} onClick={()=>{begin();onFrameStart();setCropping(structuredClone(value));}}><Crop size={13}/>Crop / zoom</button></div>{!photo&&<p role="alert" className="piece-warning">This photo is missing. Choose its original file to restore it.</p>}<div className="piece-actions"><button aria-label="Move photo earlier" disabled={slots.indexOf(slot)===0} onClick={()=>move(-1)}><ArrowLeft size={13}/>Earlier</button><button aria-label="Move photo later" disabled={slots.indexOf(slot)===slots.length-1} onClick={()=>move(1)}>Later<ArrowRight size={13}/></button></div><Select label="Piece photo fit" value={value.fit} options={[{value:'cover',label:'Fill piece'},{value:'contain',label:'Show whole crop'}]} onChange={v=>patch({fit:v as PieceEdit['fit']})}/>{value.source&&<button className="text-link" onClick={()=>patch({source:null,crop:emptyPiece().crop})}>Use main photo for this piece</button>}</>}
  <Range label="Piece rotation" value={value.rotationDeg} min={-45} max={45} step={.1} unit="°" onChange={rotationDeg=>patch({rotationDeg})} begin={begin} end={end}/>
  <details className="advanced"><summary>Position &amp; individual tone <span>+</span></summary><Range label="Piece horizontal position" value={value.offsetX} min={-20} max={20} step={.1} unit="%" onChange={offsetX=>patch({offsetX})} begin={begin} end={end}/><Range label="Piece vertical position" value={value.offsetY} min={-20} max={20} step={.1} unit="%" onChange={offsetY=>patch({offsetY})} begin={begin} end={end}/>{individual&&<><Range label="Piece exposure" value={value.exposureEv} min={-3} max={3} step={.05} unit="EV" onChange={exposureEv=>patch({exposureEv})} begin={begin} end={end}/><Range label="Piece contrast" value={value.contrast} min={-50} max={50} onChange={contrast=>patch({contrast})} begin={begin} end={end}/><Range label="Piece warmth" value={value.warmth} min={-50} max={50} onChange={warmth=>patch({warmth})} begin={begin} end={end}/></>}</details>
  <div className="piece-actions"><button onClick={()=>patch({rotationDeg:0,offsetX:0,offsetY:0,exposureEv:0,contrast:0,warmth:0})}><RotateCcw size={13}/>Reset piece effects</button></div>
  <div className="piece-actions"><button onClick={()=>{const pieces={...p.pieces};slots.forEach((s,i)=>{pieces[s.key]={...(pieces[s.key]??emptyPiece()),rotationDeg:i%2?2.4:-1.8,offsetX:i%2?.6:-.4,offsetY:0};});edit({...p,pieces});}}>Gentle stagger</button><button onClick={()=>{const pieces={...p.pieces};slots.forEach(s=>{pieces[s.key]={...(pieces[s.key]??emptyPiece()),rotationDeg:0,offsetX:0,offsetY:0};});edit({...p,pieces});}}>Align pieces</button></div>
  {cropping&&photo&&main&&<PieceFraming key={slot.key} project={p} slotKey={slot.key} pieceId={slot.id} label={slot.label} bitmap={photo.bitmap} mainWidth={main.info.width} mainHeight={main.info.height} getPreview={getPreview} onPreview={patch} onApply={()=>{end();setCropping(null);}} onCancel={()=>{patch({crop:cropping.crop,fit:cropping.fit});end();setCropping(null);}}/>}
 </section>;
}
