import fs from 'node:fs/promises';
import sharp from 'sharp';
const dir='artifacts/albums';await fs.mkdir(dir,{recursive:true});
const styles=[
 ['rounded-washi','Rounded washi','Uneven rounded corners, restrained fibres and a narrow worn rim.'],
 ['album-ivory','Ivory album paper','Warm paper with fine tooth and light aging.'],
 ['antique','Aged album page','Mottled paper, sparse foxing, edge aging and a left binding crease.'],
 ['kraft','Kraft scrapbook','Brown paper with a more directional fibre character.'],
 ['charcoal','Black album paper','Dark textured support with ivory mounting pockets.'],
 ['linen','Linen album cloth','A fine woven support with adjustable texture scale.'],
 ['mounted-sequence','Three mounted photographs','Separate photos, rounded piece corners and individual tilts.']
];
for(const id of ['rounded-washi','antique','linen']){const meta=await sharp(dir+'/'+id+'.png').metadata();await sharp(dir+'/'+id+'.png').extract({left:Math.round(meta.width*.08),top:Math.round(meta.height*.07),width:560,height:480}).png().toFile(dir+'/'+id+'-detail.png');}
const cards=styles.map(([id,name,note])=>'<article><h2>'+name+'</h2><p>'+note+'</p><a href="'+id+'.png"><img src="'+id+'.png" alt="Exported '+name+'" loading="lazy"></a><p><a href="'+id+'.png">Full PNG</a> &middot; <a href="'+id+'-settings.json" download>Settings</a>'+(['rounded-washi','antique','linen'].includes(id)?' &middot; <a href="'+id+'-detail.png">Corner detail</a>':'')+'</p></article>').join('');
const html='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Album and corner studies - Handmade Photo Studio</title><style>body{margin:0;background:#eaece5;color:#2e382b;font:16px/1.5 system-ui,sans-serif}main{max-width:1250px;margin:auto;padding:35px 22px}h1{font:42px Georgia,serif;margin-bottom:10px}h2{font:27px Georgia,serif}a{color:#3c6240}header p{max-width:900px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,380px),1fr));gap:26px}article{background:#f7f8f3;padding:20px;border:1px solid #d4dacc;border-radius:10px}img{width:100%;display:block;margin:14px 0}footer{margin-top:36px}code{font-size:13px}</style><main><header><a href="/">Open the studio</a><h1>Album and corner studies</h1><p>Actual PNG exports from renderer 0.6.0, at 2,000 to 2,400 pixels on the long side. Click a picture for full resolution.</p><p>Open <b>Album background</b> in the left panel for materials, paper age, texture, stains, binding and mounting pockets. Open <b>Paper edges</b> and choose <b>Rounded washi</b> for an uneven rounded perimeter. Adjust Corner rounding and Worn rim, or round every piece separately.</p><p>These procedural surfaces follow the material direction of the supplied references. No stock texture or artist photograph is used as a material. The photo is not sharpened or blurred by background and corner controls.</p></header><div class="grid">'+cards+'</div><footer><h2>Export and UI checks</h2><p><a href="ui-export.png">Downloaded PNG</a> &middot; <a href="ui-export.jpg">Downloaded JPEG</a> &middot; <a href="editor-desktop.png">Desktop editor</a> &middot; <a href="editor-mobile.png">Mobile editor</a> &middot; <a href="checks.json">Pixel checks</a></p><p><a href="rounded-transparent.png">Transparent rounded print</a> &middot; <a href="rounded-over-000000.png">Over black</a> &middot; <a href="rounded-over-ffffff.png">Over white</a> &middot; <a href="rounded-over-923ca8.png">Over purple</a></p><p>Transparent surroundings omit the album and mounting pockets. Image only omits all paper and album treatments.</p><p>To reuse the single-print examples, load <code>Sample/dying-sun.jpg</code>, then restore the matching settings JSON from the folder menu. When private samples are unavailable, the tests use the bundled Luca Bravo mountain-lake photograph. The sequence also uses the bundled photograph and <code>Sample/fire-night.jpg</code> (or the synthetic night fixture). Settings contain no photo data; assign the matching original to each piece when restoring a multi-photo example. Use Save on this device to keep photos and settings together.</p><p>Personal photos, reference images and generated artifacts are excluded from Git.</p></footer></main></html>';
await fs.writeFile(dir+'/index.html',html);console.log('Album gallery: http://127.0.0.1:5173/artifacts/albums/index.html');
