import fs from 'node:fs/promises';
import sharp from 'sharp';
const names=(await fs.readdir('artifacts/sample-exports')).filter(x=>x.endsWith('-handmade.png'));
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const cards=names.map(name=>{const stem=name.replace('-handmade.png','');return `<article><a href="${encodeURIComponent(name)}"><img src="${encodeURIComponent(name)}" alt="${escape(stem)} finished paper artwork" loading="lazy"></a><div><h2>${escape(stem)}</h2><a href="${encodeURIComponent(name)}" download>Download PNG ↗</a><a href="${encodeURIComponent(stem+'-settings.json')}" download>Editable settings ↗</a></div></article>`;}).join('');
await fs.writeFile('artifacts/sample-exports/index.html',`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Your prints — Handmade</title><style>*{box-sizing:border-box}body{margin:0;padding:50px 5vw;background:#eeeee6;color:#30382b;font-family:Arial,sans-serif}header{max-width:800px;margin-bottom:40px}h1{font:48px Georgia,serif;font-weight:400;letter-spacing:-2px;margin:16px 0}p{font-size:14px;line-height:1.8;color:#828e73}header>span{font-size:10px;letter-spacing:3px;color:#7c8a6c}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:28px}article{background:#f8f9f2;border:1px solid #dde2d2;padding:14px}article img{width:100%;height:450px;object-fit:contain;display:block}article>div{padding:15px}h2{font:20px Georgia,serif;margin:0 0 12px}a{color:#60724e;text-underline-offset:4px}article a[download]{font-size:11px;margin-right:16px;display:inline-block;margin-top:8px}.views{margin-top:50px;border-top:1px solid #d1dac4;padding-top:20px}.views a{margin-right:20px;font-size:12px}footer{margin-top:30px;font-size:11px;color:#8c987d;line-height:1.8}@media(max-width:600px){body{padding:25px 16px}h1{font-size:37px}article img{height:auto}}</style><header><span>HANDMADE / PHOTO STUDIO</span><h1>Seven photographs.<br/>A life on paper.</h1><p>Actual 2,000-pixel exports made with your supplied images, tuned against the local reference photographs. Open a print to inspect it at full size. To reproduce it in the editor, choose its matching original from <strong>Sample</strong>, then restore the accompanying settings JSON.</p><a href="http://127.0.0.1:5173">Open the studio ↗</a></header><main>${cards}</main><section class="views"><h2>One image. Three export views.</h2><p>The same photographic finish, with different output choices.</p><a href="three-views-object.png">Artwork object ↗</a><a href="three-views-flat.png">Flat print face ↗</a><a href="three-views-image.png">Image only ↗</a></section><footer>All processing is local. The supplied photographs remain your originals. These are digital paper simulations, with original procedural materials and authored film approximations. The reference artwork has not been copied into the application.</footer></html>`);
const composites=[];for(let i=0;i<names.length;i++){const b=await sharp(`artifacts/sample-exports/${names[i]}`).resize(380,420,{fit:'contain',background:'#e9ebe2'}).png().toBuffer();composites.push({input:b,left:i%3*400+10,top:Math.floor(i/3)*470+10});const label=names[i].replace('-handmade.png','');composites.push({input:Buffer.from(`<svg width="390" height="35"><text x="12" y="24" font-size="14" font-family="Arial" fill="#506442">${escape(label)}</text></svg>`),left:i%3*400+5,top:Math.floor(i/3)*470+430});}await sharp({create:{width:1200,height:Math.ceil(names.length/3)*470,channels:3,background:'#e9ebe2'}}).composite(composites).jpeg({quality:94}).toFile('artifacts/final-samples-contact.jpg');
await sharp('artifacts/sample-exports/fire-night-handmade.png').extract({left:340,top:650,width:720,height:400}).png().toFile('artifacts/tear-detail.png');
console.log('Gallery and export contact sheet written.');
